mantl/mantl

examples/hello-world/README.md
roles/mesos/tasks/follower.yml

Running vagrant up and trying the hello world example failed to
start the hello world containers. checking the logs i noticed the
mesos-slave kept failing. The existence of `/etc/mesos-slave/?checkpoint`
prevents the slave from starting.
Found references to the checkpoint flag and ultimately landed at the
[mesos changelog](https://github.com/apache/mesos/blob/master/CHANGELOG)
* Deprecations:
* [MESOS-444] - Slave checkpoint flag has been removed as it will be enabled for all slaves.
Tracked down version of mesos installed.
`Mar 26 16:17:33 localhost yum[5144]: Installed: mesos-0.22.0-1.1.centos701406.x86_64`
`vagrant destroy`
remove checkpoint flag creation froom roles/mesos/tasks/follower.yaml
`vagrant up`
hello-world deploys correctly
`examples/hello-world/launch.sh -c …

Deprecated checkpoint flag prevents mesos-slave startup

---

roles/dnsmasq/handlers/main.yml
roles/dnsmasq/tasks/main.yml
site.yml

I'm proposing splitting the `all` play in site.yml into individual plays.
Ansible runs the handlers at the end of the play. With all of the roles in a list, the handlers aren't run until all of the roles are complete. This can cause installation issues due to dependencies. Splitting the plays out causes the handlers to run after the role is complete.

Proposed layout for site.yml and fixed dnsmasq demonstration

---

roles/mesos/README.rst
roles/mesos/defaults/main.yml
roles/mesos/tasks/follower.yml
roles/mesos/tasks/leader.yml
roles/mesos/templates/master-credentials.j2
roles/mesos/templates/master-defaults.j2
security-setup

PR for #115.
This also adds a task in `security-setup` to deprecate values that had previously been set. I'd like feedback on that, especially from @stevendborrelli and @keithchambers, but also from anyone who cares about it.

automatically generate mesos auth flags

---

roles/docker/tasks/main.yml

This PR works around an upstream issue with docker RPM Packaging.
Discussed in https://github.com/CiscoCloud/microservices-infrastructure/issues/161
Simple change. Testing now. Will confirm when complete on CCS CentOS7 base image.

Workaround for docker/issues/12108 added

---

inventory/group_vars/all/all.yml
inventory/group_vars/dc1
inventory/group_vars/dc2
openstack/provision-hosts.yml

Provide the ability for installer to specify their security group for Openstack in the configuration file instead of directly within the playbook.

Move openstack security group to a variable

---

README.md

The box used in the Vagrantfile isn't compatible with VMware Fusion. Note
that Virtualbox is the only supported Vagrant provider.

Note Vagrant provider requirement

---

security-setup

security-setup fails on Windows because openssl interprets the Windows separator character ("\") as escape.  Fixed by changing os.path to posixpath throughout.

Update security-setup for Windows compatibility

---

ssl/openssl.cnf

see https://community.qualys.com/blogs/securitylabs/2014/09/09/sha1-deprecation-what-you-need-to-know

generate sha256 signed CA/certs by default

---

playbooks/show-uptime.yml

Awk can read `/proc/uptime` directly, so no need to pipe it output from cat.

Have awk read /proc/uptime directly

---

inventory/group_vars/name_node
roles/hdfs-standalone/defaults/main.yml
roles/hdfs-standalone/templates/hadoop.sh.j2
roles/spark/defaults/main.yml
roles/spark/tasks/main.yml
roles/spark/templates/spark.sh.j2

- Now spark-shell can be installed at many nodes
- use inventory/group_vars/name_node  to setup FQDN for NameNode
IssueID: DE3046

Small fixes for Spark role

---

inventory/group_vars/data_nodes
spark.yml

- create data_nodes invetory file with correct NameNode HDFS URL
- Install spark-shell at workes/slaves instead master node

Hotfix: datanode used wron hdfs-site.xml

---

docs/security/security.rst

In CentOS the correct path is /etc/sysconfig/docker.

Set correct path for the Docker options file

---

roles/kafka/README.md
roles/kafka/defaults/main.yml
roles/kafka/tasks/client.yml

Add default settings:
- kafka_brokers that define how many brokers you plan to use in
cluster
- kafka_broker_memory define Java memory settings as far
kafka_broker_heap will define Java heap size.
To be remembered that heap size always at least twice smaller than
memory value. Default 2048 for Java memory and 1024 for Java
heap.
FeatureID: none

Kafka: add ability to setup number and setting for brokers

---

docs/security/security_setup.rst
security-setup

Fixes issues raised in #239, and documented in #247 and #248. Current help string:
```
usage: set up authentication and security for various components
optional arguments:
-h, --help            show this help message and exit
--change-admin-password
change admin password during this run (default: False)
Broad Disable Options:
disable security for entire components. This overrides any more specific options set from the sections below.
--disable             disable all security. This overrides everything. (default: False)
--consul CONSUL       Enable Consul security. This overrides all other Consul options. (default: True)
--mesos MESOS         Enable Mesos security. This overrides all other Mesos options. (default: True)
--marathon MARATHON   Enable Marathon security. This overrides all …
```

clean up security-setup options

---

roles/consul/tasks/main.yml

This is to prevent the restart handler kicking off
before the scripts they use are installed.

Move flush-hanlders after script installations

---

inventory/group_vars/dc1
inventory/group_vars/dc2
openstack/provision-hosts.yml

Provide the ability to add metadata key/value pairs to hosts within
Openstack.
Use Case:
Deploy applications to hosts with ansible using inventory plugin that can
query hosts via novaclient and be grouped based on attributes within the
hosts metadata.

[FEATURE] Add metadata to hosts in Openstack

---

requirements.txt

There was a bug introduced during 1.9 as plan is to deprecate the
module in favor of a new module. The output from the server state
returns back the ip addresses as list instead of strings.
A fix was applied such that 1.9.0.1 returns a string as expected.
By capping the version of ansible to 1.9.0.1, then any openstack
related playbooks will work normally.
See issue #316 for additional details.

[BUGFIX] ansible nova_compute module bug

---

roles/kafka/README.md
roles/kafka/defaults/main.yml

For small cluster change kafka_memory and kafka_heap value from
2048 and 1024 to 512 and 256
FeatureID: Internal

Change default memory values for Kafka brokers

---

site.yml

In multi-datacenter deployment task "install nginx admin password" from
consul role should run on both datacenters, but only once, so the task
itself has a flag "run_once" and we separate consul deployment to 2
datacenters

Fix for "install nginx admin password" task in consul role

---

roles/common/defaults/main.yml
roles/common/tasks/main.yml
roles/dnsmasq/handlers/main.yml
roles/dnsmasq/tasks/main.yml

Previously:
- NetworkManager would manage DNS via dnsmasq
- if interfaces were brought up with cloud-init (as on GCE) NetworkManager would not start the dnsmasq instance. Additionally, if dnsmasq died NetworkManager would not necessarily restart it.
- NetworkManager would overwrite `/etc/resolv.conf`
Now:
- dnsmasq is managed by systemd, which will keep it alive
- NetworkManager's DNS settings are disabled
- the default DNS servers are used for domains other than `consul_dns_domain`, since we can specify separate search settings.
I'd appreciate if someone could test this on OpenStack and another Vagrant machine. I've already tested that the `/etc/resolv.conf` will survive across changing the hostname via `nmcli gen hostname {new name}` and rebooting, two instances in which NM would …

manage DNS with dnsmasq alone

---

Vagrantfile

On systems with more than 5 ssh-keys added, ansible provisioner will fail with:
```
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/adam/workspace/microservices-infrastructure/.vagrant/machines/default/virtualbox/private_key --user=vagrant --connection=ssh --limit='default' --inventory-file=/Users/adam/workspace/microservices-infrastructure/.vagrant/provisioners/ansible/inventory --extra-vars={"consul_acl_agent_token":"64f3ecc3-82e1-47e6-82a9-88be854a6d1c","consul_acl_master_token":"66569297-caf6-480f-a87d-41f65b5dc71a","consul_default_acl_policy":"allow","consul_gossip_key":"IVVoL8KWLPs73sFG82RSVA==","do_consul_acl":true,"do_consu …
```

Workaround for Vagrant < 1.7.3 and host with > 5 ssh-keys

---

Dockerfile

Dockerfile is missing `openssh`
After doing a complete build using the Dockerfile base image, that was the only change I had to make.

added openssh to image

---

roles/kafka/tasks/client.yml

Issue: Timeout when waiting for host-04:7000
In case slow network or some performance issue kafka-sheduler need
more than 300 sec (default for wait_for ansible module) to be
deployed on top of marathon.
Change "timeout" value to 900 that increase maximum number of
seconds to wait for Kafka-sheduler
IssueID: INTERNAL

Kafka depploy is failing because connection timeout

---

roles/spark/README.md
roles/spark/defaults/main.yml
roles/spark/tasks/client.yml
roles/spark/templates/log4j.properties.j2
roles/spark/templates/spark-env.sh.j2

Setup and configure spark log4j
- add global variable SPARK_HOME to specify spark config directory
- add spark_log4j_host and spark_log4j_port defaults to set log
server hostname and port
FeatureID: INTERNAL

Enable log4j for Spark

---

roles/logstash/templates/logstash-service.j2

Since we use `@@localhost:1514` to forward logs with rsyslog, we need to set the correct transport protocol in the systemd unit file.

Change Logstash syslog plugin port to TCP

---

docs/getting_started/index.rst

In case users run OSes like Arch that have Python3 defaults.
Looks like vim also deleted whitespace at the end of a few lines.

Added note on Ansible Python versions

---

docs/components/chronos.rst
docs/security/security_setup.rst
inventory/1-datacenter
inventory/2-datacenter
roles/chronos/README.rst
roles/chronos/defaults/main.yml
roles/chronos/files/chronos-consul.cfg
roles/chronos/handlers/main.yml
roles/chronos/meta/main.yml
roles/chronos/tasks/framework_auth.yml
roles/chronos/tasks/main.yml
roles/chronos/tasks/nginx-proxy.yml
roles/chronos/templates/chronos-consul.j2
roles/chronos/templates/chronos-iptables.tmpl.j2
roles/chronos/templates/chronos.nginx.j2
roles/chronos/templates/nginx-chronos.env.j2
roles/chronos/templates/nginx-chronos.service.j2
security-setup
site.yml

Chronos
=======
[Chronos](http://mesos.github.io/chronos) It is a distributed and fault-tolerant scheduler that runs on top of Apache Mesos that can be used for job orchestration. It supports custom Mesos executors as well as the default command executor. 
Thus by default, Chronos executes sh (on most systems bash) scripts.
Chronos listens on port 4400.

Add Chronos ansible role

---

docs/components/opeconnect.rst
inventory/1-datacenter
inventory/2-datacenter
roles/openconnect/README.rst
roles/openconnect/defaults/main.yml
roles/openconnect/handlers/main.yml
roles/openconnect/tasks/certificates.yml
roles/openconnect/tasks/configure.yml
roles/openconnect/tasks/install.yml
roles/openconnect/tasks/main.yml
roles/openconnect/tasks/networking.yml
roles/openconnect/templates/ca.tmpl.j2
roles/openconnect/templates/gen_certs.sh.j2
roles/openconnect/templates/ocserv.conf.j2
roles/openconnect/templates/ocserv.service.j2
roles/openconnect/templates/server.tmpl.j2
vpn-server.yml

This playbook installs OpenConnect VPN SSL server role.
To run playbook just execute ansible-playbook -i inventory/1-datacenter vpn-server.yml.
The role will be installed on the host-02 by default. You can change this in inventory files or vpn-server.yml.
Make sure you change default username:password pair in the openconnect_users variable before deploying this role to the server.
The detailed info about the role is in the README file.

Added OpenConnect VPN role

---

roles/zookeeper/files/zookeeper-wait-for-listen.sh
roles/zookeeper/handlers/main.yml

When ansible runs in vagrant the $HOSTNAME variable has localhost.localdomain.

Add command line argument for hostname to zookeeper-wait-for-listen.sh

---

README.md

and fixed a small typo.
Specifically, `inventory/1-datacenter` and such don't even exist anymore, so we probably shouldn't talk about them in the README. Rather, we have great and mostly always up-to-date documentation, so we can just direct interested users there.

Updated README to point to docs w/r/t provisioning

---

terraform/openstack/hosts/main.tf
terraform/openstack/keypair/main.tf

While trying to make **terraform plan** or **apply** we're geting this error:
Errors:
* 1 error(s) occurred:
* module.dc2-hosts: missing dependency: module.dc2-keypair.output.region
The reason is missing output for **region** in **openstack/keypair/main.tf**.

Fixed error for OpenStack Terraform module

---

roles/collectd/tasks/main.yml
roles/docker/tasks/collectd.yml
terraform.sample.yml

Bug in ansible collectd role which affects master branch deployment.
Ansible output:
```
TASK: [docker | install collectd docker plugin] ***************************** 
failed: [qa3-worker-02] => (item=dockerplugin.py) => {"checksum": "a643733cc27e880197f40925ba045aac59d11788", "failed": true, "item": "dockerplugin.py"}
msg: Destination directory /usr/share/collectd/plugins does not exist
TASK: [docker | configure collectd docker plugin] *************************
failed: [qa3-control-03] => {"checksum": "7d8913212991dd5b5a7ac2dd7ffa96a8b06a19d7", "failed": true}
failed: [qa3-worker-02] => {"checksum": "7d8913212991dd5b5a7ac2dd7ffa96a8b06a19d7", "failed": true}
msg: Destination directory /etc/collectd.d does not exist
msg: Destination directory /etc/collectd.d does not exist
```

Bug in ansible collectd role

---

roles/marathon/tasks/conf.yml
roles/mesos/tasks/main.yml
roles/mesos/templates/hostname.j2

Please review. This seems to really improve the reliability of provisioning a cluster on AWS and helps with https://github.com/CiscoCloud/microservices-infrastructure/issues/363. Thanks @ChrisAubuchon

use consul dns for mesos and marathon

---

roles/collectd/tasks/main.yml

Removes redundant directory creation code (/etc/collectd.d is create by collectd package install [as shown on fresh CentOS install](https://gist.github.com/corebug/91af0205f34655ce3ecf)).

Remove redundant code.

---

Dockerfile
docker_launch.sh
docs/getting_started/dockerfile.rst
docs/getting_started/index.rst
playbooks/wait-for-hosts.yml
plugins/inventory/terraform.py

@stevendborrelli @kenjones-cisco I ended up using a centos base for the
Dockerfile for now. I ran into several issues using alpine. The pre-built
Terraform binaries do not run (I believe due to glibc issues [1]) and building
Terraform from source also was not cooperating (building 0.5.3 appears to broken
[2] due to a relocated dependency repo and there are issues with the AWS
provider on master).
Some potential improvements:
1. Make it easier to manage your cluster with a more sophisticated launch
script. Right now, the script will automatically provision your cluster. But
if you want to modify (or destroy) your cluster, you have to just
launch the container with bash and run the commands manually.
2. If we publish a public container, we should add some documentation about
using it as a …

support for Terraform in Dockerfile

---

Vagrantfile
roles/chronos/README.rst
roles/chronos/defaults/main.yml
roles/chronos/files/chronos-consul.cfg
roles/chronos/handlers/main.yml
roles/chronos/meta/main.yml
roles/chronos/tasks/framework_auth.yml
roles/chronos/tasks/main.yml
roles/chronos/tasks/nginx-proxy.yml
roles/chronos/templates/chronos-consul.j2
roles/chronos/templates/chronos-iptables.tmpl.j2
roles/chronos/templates/chronos.nginx.j2
roles/chronos/templates/nginx-chronos.env.j2
roles/chronos/templates/nginx-chronos.service.j2
security-setup
terraform.sample.yml
terraform/aws/aws.tf
terraform/gce/gce.tf
vagrant.yml

Chronos
=======
[Chronos](http://mesos.github.io/chronos) It is a distributed and fault-tolerant scheduler that runs on top of Apache Mesos that can be used for job orchestration. It supports custom Mesos executors as well as the default command executor. 
Thus by default, Chronos executes sh (on most systems bash) scripts.
Chronos listens on port 4400.

Add Chronos role

---

terraform/openstack/hosts/main.tf

The cloud provider's default secgroup is a reasonable default,
as it will allow traffic between other vms also on the default
secgroup.

OpenStack: Use default security group

---

plugins/inventory/terraform.py
terraform/gce/gce.tf
terraform/openstack/hosts/main.tf
terraform/openstack/keypair/main.tf

Image usernames aren't always set at the values we provide, so let's make them configurable.
(notable exceptions: AWS already provides this dynamically and we use it, and DO is always "root")

terraform.py username

---

roles/logstash/README.rst
roles/logstash/templates/logstash.conf.j2

Example: set the following in your playbook
```
logstash_output_elasticsearch:
host: "elasticsearch.example.com"
protocol: "http"
```

logstash: optionally specify elasticsearch output

---

roles/mesos/tasks/nginx-proxy.yml

There was a duplicate tags instruction which should be a notify.

Typo error in mesos/nginx-proxy.yml

---

roles/marathon/tasks/conf.yml

In order to run docker images from private repositories we should have an artifact store for marathon.
Ref http://container-solutions.com/pulling-from-a-private-docker-repository-with-marathon/

Adding marathon artifact store

---

Dockerfile
docker_launch.sh
docs/getting_started/dockerfile.rst

The experience running a build from a docker container wasn't great if you had a passphrase-protected ssh key. Also, there was no way to build a cluster if you used a key other than one named ~/.ssh/id_rsa. This should fix both of those issues.

dockerfile ssh: support passphrase and any key name

---

playbooks/upgrade-packages.yml

playbooks/upgrade-packages.yml has been edited to run `yum clean all` prior to refreshing the cache or making any upgrades.

upgrade-packages.yml cleans yum prior to upgrading

---

roles/kafka-mesos/tasks/client.yml
roles/kafka-mesos/tasks/main.yml
roles/kafka-mesos/templates/kafka.json.j2
roles/marathon/defaults/main.yml

Start brockers using consul-dns record instead hardcoded node fqdn

Kafka-mesos: remove host fqdn dependency

---

roles/kafka/tasks/main.yml

Error: cannot create directory ‘/usr/local/share/kafka/kafka_2.10-
0.8.2.1/bin/../logs’: Permission denied
Create logs directory with mode 0775
IssueID: Internal

Fix: kafka not able to write to log folder

---

roles/chronos/templates/chronos-consul.j2
roles/consul/files/distributive-consul-config.json
roles/consul/files/docker-service.json
roles/marathon/templates/marathon-consul.j2
roles/zookeeper/templates/zk-consul.json.j2

Previously, the checks were defined without
a timeout, which led to thousands of processes
spawned by consul. This would worsen the
health of an already unstable cluster.
In particular, the curl command by default has
no timeout, and will hang if it successfully
opens a TCP connection but receives no data.

All consul checks must have timeouts

---

security-setup

Fixes #536. Doesn't need testing on cloud deployments or anything, just run ./security-setup locally.

Decode errors in security-setup before printing

---

roles/consul/tasks/distributive.yml

I've changed the role/consul/tasks/distributive.yml so that it only installs and registers the consul test if it is a control node. This is to correct #540. 
It will still run the consul checks a single time to verify the initial install is correct. 
Testing has only been done via vagrant, however I modified the vagrant.yml playbook so that it will have the consul_servers_group variable set as `role=worker` as it would via the terraform playbook.

Corrected distributive ansible tasks for consul

---

roles/chronos/defaults/main.yml
roles/marathon/defaults/main.yml
roles/mesos/defaults/main.yml
roles/zookeeper/defaults/main.yml
roles/zookeeper/templates/zookeeper-service.j2

* uses new version of zookeeper container with zookeepercli built in
* uses zookeepercli to set zk acls instead of the setacl.sh script (https://github.com/CiscoCloud/microservices-infrastructure/issues/329).
* zookeeper-service systemd unit has been updated to use the certificates in /etc/consul/ssl for ssl validation.
Note that the zookeeper container includes an updated version of consul-template (v0.10.0) which has a bug (https://github.com/hashicorp/consul-template/issues/321) where it ignores some command line flags such as `--ssl-verify`. To mitigate this (and for better ssl support in general), the zookeeper container now allows you to mount a host volume with certificates to use for ssl verification.

zk container - manage zk cls with zkcli and add certs

---

docker_launch.sh

If the SSH_KEY already exists then no need to check the /ssh/ volume
for keys, so we can skip this step.
closes: #555

[TASK] Make docker_launch flexible

---

requirements.txt
roles/chronos/tasks/main.yml
roles/dnsmasq/tasks/main.yml
roles/dnsmasq/templates/10-consul
roles/dnsmasq/templates/resolv.conf.j2
roles/marathon/tasks/main.yml

* ensure zookeeper is available before starting marathon and chronos (fixes #533)
* preserve internal dns resolution (improves #538 but #544 also needed)
* require at least ansible 1.9.1 so that services can properly be enabled/disabled (fixes #549)

attempting to improve recovery of a cluster post-reboot

---

roles/chronos/tasks/main.yml

In a Vagrant build, sometimes zookeeper is occasionally not available when Chronos is restarted.

Use zookeeper-wait-for-listen to check if zookeeper is up

---

roles/common/tasks/main.yml

My CentOS 7 version that I had didn't have firewalld installed so the ansible script failed.  I updated the common role so that if firewalld is not installed it won't error out if it tries to disable a service that isn't there.

Error detection in firewalld

---

terraform/openstack.sample.tf
terraform/openstack/hosts/main.tf

An example from one of my roles on how used made use of the block devices:
```
- name: create a virtual group named vgdata on device /dev/vdb
sudo: yes
lvg:
vg=vgdata
pvs=/dev/vdb
state=present
- name: create a logical volume named lvdata01 in vgdata
sudo: yes
lvol:
vg=vgdata
lv=lvdata01
size=100%FREE
state=present
- name: create an ext4 filesystem in /dev/mapper/vgdata-lvdata01
sudo: yes
filesystem:
fstype=ext4
dev=/dev/mapper/vgdata-lvdata01
- name: mount data filesystem
sudo: yes
mount:
name=/srv/gluster/data
src=/dev/mapper/vgdata-lvdata01
fstype=ext4
state=mounted
- name: start GlusterFS service
sudo: yes
service:
name=glusterd
state=started
- name: create database gluster volume
sudo: yes
run_once: true
gluster_volume:
host="{{ inventory_hostname }}"
brick=/srv/gluster/data/brick …
```

openstack terraform changes for mounting block devices for used with glusterfs

---

docs/getting_started/openstack.rst
plugins/inventory/terraform.py
terraform/openstack-floating.sample.tf
terraform/openstack/hosts-floating/main.tf

Give users the option of using an alternate sample for OpenStack
depending on whether they want to use a private network with floating
IPs or a public network.

OpenStack floating ip support

---

docs/getting_started/index.rst
docs/getting_started/softlayer.rst
terraform/softlayer.sample.tf
terraform/softlayer/hosts/main.tf
terraform/softlayer/keypair/main.tf

This adds .tf files for SoftLayer virtual guests,
and a simple .tf file for using them.
The change also depends on terraform.py being updated
so that it can read the inventory list from softlayer.tfstate.

Add support for SoftLayer

---

terraform/aws.sample.tf
terraform/digitalocean.sample.tf
terraform/gce.sample.tf
terraform/openstack-floating.sample.tf
terraform/openstack.sample.tf
terraform/softlayer.sample.tf
terraform/vsphere.sample.tf

Standardize on 3 control servers and 3 worker nodes in the sample Terraform files

Set control_count and worker_count to 3 by default

---

roles/marathon/tasks/jobs.yml

The event subscription was failing without specifying the Content-Type in the request.

fix marathon-consul event hook registration

---

roles/haproxy/README.rst
roles/haproxy/defaults/main.yml
terraform/aws/aws.tf
terraform/gce/gce.tf

* haproxy was broken when Consul SSL was disabled. It should now work whether Consul SSL is enabled or not
* opens HTTP/S ports on AWS and GCE 
* fixes a broken link in the haproxy role's README

Fix a few haproxy issues

---

roles/zookeeper/files/zookeeper_check.sh
roles/zookeeper/templates/zk-consul.json.j2

The zk checker script originally rely on `$HOSTNAME`. This will not work in all cases. I've modified to the script to optionally accept `host` as an argument and modified the consul check to use `inventory_hostname` when using the `zk_checker.sh` script.

Zookeeper consul check fix

---

plugins/inventory/terraform.py

On AWS, after provisioning GlusterFS in MI and refreshing your Terraform state, you end up with control node `ebs_block_device` definitions in your `tfstate` that look something like this:
```json
"ebs_block_device.3075786550.delete_on_termination": "false",
"ebs_block_device.3075786550.device_name": "xvdh",
"ebs_block_device.3075786550.encrypted": "false",
"ebs_block_device.3075786550.iops": "300",
"ebs_block_device.3075786550.snapshot_id": "",
"ebs_block_device.3075786550.volume_size": "100",
"ebs_block_device.3075786550.volume_type": "gp2",
```
Note that this doesn't use an `n` based index and is not compatible with `parse_attr_list` in `terraform.py`:
```shell
$ python plugins/inventory/terraform.py --list
Traceback (most recent call last):
File "plugins/inventory/terraform.py", line …
```

fix terraform.py to handle aws ebs_block_device

---

docs/getting_started/ssh_users.rst

If a user copies the code from the documentation into a users.yml file, all users will be skipped:
`enable -> enabled`

Correct variable name for enabling a user

---

roles/glusterfs/tasks/main.yml
roles/glusterfs/tasks/server.yml

Installation would fail when no brick device is specified, which is the default case on anything but GCE, AWS, and OpenStack.
This fixes issue https://github.com/CiscoCloud/microservices-infrastructure/issues/636

Skip GlusterFS installation when no device is specified

---

docs/security/security_setup.rst
roles/docker/README.rst
roles/docker/tasks/main.yml
roles/docker/templates/config.json.j2
security-setup

You can configure microservices-infrastructure to pull from private
docker registries (including hub.docker.com), this requires
credentials.
In order to set up credentials, run the security-setup script
with the option "--use-private-docker-hub=true" (defaults to false).
Even if you use a private hub, you will be able to pull public/official
images from the official, open docker hub.
The ansible task will insert the credentials into
/root/.docker/config.json
where the docker daemon will pick them up.
Also, some documentation was added.

Add support for private Docker registries

---

roles/docker/tasks/main.yml

This is a follow up to #644. Pulling from a private docker registry worked fine on the command line, but from Marathon it didn't work, I guess because of Mesos' sandbox that didn't give Docker access to /root/.docker/config.json. This patch follows the [official Marathon guide](https://mesosphere.github.io/marathon/docs/native-docker-private-registry.html) on how to use private registries.
@ryane I'm sorry I didn't test #644 properly on Marathon with the newest Docker version! At least now it works in Marathon too :wink:

Add Docker credentials to /etc

---

roles/docker/handlers/main.yml
roles/docker/tasks/main.yml
roles/logrotate/files/docker
roles/logrotate/tasks/main.yml

Force docker to use syslog log driver, and then use logrotate to rotate the syslog logs.
As per Issue https://github.com/CiscoCloud/microservices-infrastructure/issues/500.

Issue #500 - docker log rotation

---

roles/logstash/templates/logstash-service.j2
roles/logstash/templates/logstash.conf.j2

Problem: Logstash didn't understand values coming from collectd:
:message=>"Invalid value for type=\"cpu.usage\", key=nil, index=3",
:level=>:error
This was because logstash's collectd input wasn't configured with
types.db for Docker stats.
This commit mounts the collectd plugin volume into the logstash
container, and configures logstash so it reads types.db for the
docker-collectd plugin.

Fix collectd->logstash input types

---

terraform.sample.yml

This is a common gotcha that bites people, and it's a bit difficult to debug.
Let's disable it by default, since most people will probably start with a single DC anyways.
See #648

Comment out consul_acl_datacenter by default

---

terraform/openstack/hosts-floating/main.tf
terraform/openstack/hosts/main.tf
terraform/vsphere/main.tf

The worker nodes name are inconsistent. For some providers it is
short_name-control-xx while others are short_name-control-xxx.
This commit sets the worker nodes name to short_name-control-xxx for all providers.

Consistent naming of worker nodes.

---

docs/getting_started/dnsimple.rst
docs/getting_started/index.rst
docs/index.rst
terraform.sample.yml
terraform/aws.sample.tf
terraform/aws/aws.tf
terraform/digitalocean.sample.tf
terraform/digitalocean/hosts/main.tf
terraform/dnsimple/dns/main.tf
terraform/gce.sample.tf
terraform/gce/gce.tf
terraform/openstack-floating.sample.tf
terraform/openstack.sample.tf
terraform/openstack/hosts-floating/main.tf
terraform/openstack/hosts/main.tf
terraform/softlayer.sample.tf
terraform/softlayer/hosts/main.tf
terraform/vsphere.sample.tf
terraform/vsphere/main.tf

This means you will get actual DNS records for your mi cluster, which makes it much easier to work with.
I have already tested this with SoftLayer and dnsimple. It would be great if somebody could test it with the other clouds as well!

Support for DNS providers

---

mi-deploy/mi-deploy.go

Will cause mi-deploy to be successful on the first run more often. 
Fixes #711, see #709.

mi-deploy: wait for hosts to be ready before SSH

---

roles/consul/tasks/acl.yml

Mantl can run in a multi-DC configuration. When
we're setting up a DC with another DC as the ACL
master, we shouldn't upsert ACLs (which should be
done in that DC)

Only set ACL when this is the primary datacenter

---

roles/haproxy/README.rst

Add instructions on how to use the local haproxy with Terraform's DNS records.
GitHub user @kecorbin raised this issue on gitter.im.

Update Haproxy README

---

terraform/aws/aws.tf

* 20 GB chosen arbitrarily
* other providers need similar capability

configurable root volume size on aws

---

roles/handlers/defaults/main.yml

This sets the default log level to info

Update nginx-consul container to 1.2

---

roles/calico/README.rst
roles/calico/defaults/main.yml

This PR should close issues https://github.com/CiscoCloud/microservices-infrastructure/issues/696 and https://github.com/CiscoCloud/microservices-infrastructure/issues/704.

Register ports of the "-direct" Calico services in Consul

---

docs/security/security_setup.rst
roles/calico/files/executor_environment_variables
roles/calico/tasks/main.yml
roles/calico/templates/executor_environment_variables
roles/common/tasks/main.yml
roles/docker/defaults/main.yml
roles/mesos/defaults/main.yml
security-setup

This includes changes that will allow the supported packages  to run on Mantl via mantl-api. It includes a new mesos credential, the `unzip` package (used by some of the frameworks), fixes a bug with the Calico integration, and increases the range of port resources offered for mesos.

mantl-api support

---

terraform/openstack/hosts-floating/main.tf

Adding GlusterFS volume for floating-ip Terraform config, fixes https://github.com/CiscoCloud/microservices-infrastructure/issues/730.

Add GlusterFS volume setup for floating-ip configuration

---

docs/getting_started/gce.rst
docs/getting_started/index.rst
terraform/aws.sample.tf
terraform/digitalocean.sample.tf
terraform/gce.sample.tf
terraform/gce/dns/main.tf
terraform/openstack-floating.sample.tf
terraform/openstack.sample.tf
terraform/softlayer.sample.tf
terraform/vsphere.sample.tf

This can be used instead of DNSimple for DNS records.
Also adds some documentation for the provider.

Add support for Google Cloud DNS

---

terraform/aws/aws.tf

With this fix, both worker and control instance can have an iam_instance_profile associated in aws platform.
Two vars are defined in aws.tf
* control_iam_profile
* worker_iam_profile

Add support of iam_instance_profile settings for aws.

---

roles/marathon/defaults/main.yml
roles/marathon/templates/mesos-consul.json.j2

#791 
Tested on GCE, will test on AWS and DO next. 
```
[centos@lb-mi-control-01 ~]$ sudo docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
ciscocloud/mesos-consul      v0.3                df2f1189d63c        3 hours ago         15.62 MB
```
```
[centos@lb-mi-worker-001 ~]$ sudo docker ps
CONTAINER ID        IMAGE                               COMMAND                CREATED             STATUS              PORTS                                                                      NAMES
3c7f977d57a9        ciscocloud/mesos-consul:v0.3        "/bin/mesos-consul -   5 minutes ago       Up 5 minutes       
```
```
[centos@lb-mi-worker-001 ~]$ curl localhost:8500/v1/catalog/services
{
...
"mesos-consul":[
],
...
}
```

Update mesos consul image version to 0.3.0

---

roles/mantlui/defaults/main.yml

Update to Mantl UI 0.3, which is a major visual update and lays the groundwork for future improvements to the management interface.
The new repo for the frontend components of the UI is at https://github.com/CiscoCloud/mantl-ui-frontend
And it looks like this:

mantlui: bump to 0.3

---

roles/docker/tasks/lvm.yml
roles/docker/tasks/main.yml

Revert to using centos docker:
- remove local overrides in systemd
- use environment files in /etc/sysconfig
See #688 for the rationale for using the CentOS packages.

Use centos docker instead of docker inc's version

---

roles/consul/defaults/main.yml
roles/consul/templates/consul.json.j2

Fixes #667
Tested on GCE
```
[root@lb-mi-control-01 consul]# cat consul.json
{
"datacenter": "lb-gce-dc",
"advertise_addr": "10.0.0.2",
"node_name": "lb-mi-control-01",
"rejoin_after_leave": true,
"domain": "consul",
"retry_join": [ "10.0.0.4", "10.0.0.2", "10.0.0.5" ],
"server": true,
"bootstrap_expect": 3,
"encrypt": "gvw3HlRllZDcClmukVn6sQ==",
"ca_file": "/etc/consul/ssl/ca.cert",
"cert_file": "/etc/consul/ssl/consul.cert",
"key_file": "/etc/consul/ssl/consul.key",
"verify_incoming": true,
"verify_outgoing": true,
"data_dir": "/var/lib/consul",
"ui_dir": "/usr/share/consul-ui",
"enable_syslog": true,
"disable_remote_exec": true,
"http_api_response_headers": {
"Access-Control-Allow-Origin": "*"
},
"dns_config": {
"allow_stale": true,
"max_stale": "5s"
}
}
[root@lb-mi-control-01 consul]# …
```

Add support for 5s of stale DNS reads in Consul

---

roles/logstash/templates/logstash-service.j2
roles/logstash/templates/logstash.conf.j2
roles/mantlui/templates/mantlui.nginx.j2
roles/marathon/defaults/main.yml
roles/marathon/tasks/jobs.yml
roles/marathon/templates/mantl-api.json.j2
roles/mesos/tasks/follower.yml
roles/mesos/templates/mantl-api-credential.j2

mantl-api integration. It is accessible at /api on control nodes.
This also includes a fix for the logstash role that had broken the vagrant build (#782)

mantl-api installed by default

---

roles/mantlui/defaults/main.yml

update to 0.4, which adds health checks
visual diff: https://github.com/CiscoCloud/mantl-ui-frontend/commit/37ea0e74ccd879d58aea08c486670134a12546dd

mantlui: update to 0.4

---

.gitignore
docs/getting_started/openstack.rst
terraform/aws/aws.tf
terraform/gce/gce.tf
terraform/openstack-floating.sample.tf
terraform/openstack.sample.tf
terraform/openstack/hosts-floating/main.tf
terraform/openstack/hosts/main.tf

100GB volumes don't look quite reasonable for control nodes.
Added appropriate options to Terraform files.

Add different LVM volume sizes for control and resource nodes.

---

roles/marathon/defaults/main.yml

0.1.1 enables custom packages (packages that don't exist in the mesosphere universe)

mantl-api: bump version

---

roles/common/files/10-root-nofiles.conf
roles/common/tasks/main.yml
roles/consul/tasks/main.yml

This removes ansible roles that are superseded by my PR in ciscocloud/consul-rpm#1. This code was broken on older versions of ansible, so that will also fix #814

Removing ansible roles that are superseded by consul-rpm (PR#1)

---

roles/mantlui/defaults/main.yml

Fixes a few bugs that I've noticed while preparing (Mantl) 0.5. Namely:
- healthchecks wouldn't update while focused on a single healthcheck. Now they do.
- clicking the health status of a service would take you to the overall health page. Now it takes you to the specific health checks of the service you clicked on.
It also adds logos for Traefik when we are able to add that to the UI.

mantlui: update to 0.5

---

packer/vagrant.json

we need to push a new vagrant image with Atlas.
Currently, the vagrant build is broken when installing Docker due to the `docker-engine conflict` error #688.

vagrant: update packer provisioning

---

roles/glusterfs/defaults/main.yml

This PR updates glusterfs repo checksum. So, solve this error:
```
TASK: [glusterfs | enable community repo] ************************************* 
failed: [mi-control-02] => {"failed": true}
msg: The SHA-256 checksum for /etc/yum.repos.d/glusterfs-epel.repo did not match 2e2e85fe728b04d19be098b218bd70e304bc33bdf55cbdb8ab86b9d65e7d8538; it was ee06398d5b09d230fa3ffad4995b83089012a426265741c58a70bf587d14613c.
failed: [mi-control-01] => {"failed": true}
msg: The SHA-256 checksum for /etc/yum.repos.d/glusterfs-epel.repo did not match 2e2e85fe728b04d19be098b218bd70e304bc33bdf55cbdb8ab86b9d65e7d8538; it was ee06398d5b09d230fa3ffad4995b83089012a426265741c58a70bf587d14613c.
FATAL: all hosts have already failed -- aborting
```

Updates glusterfs repo checksum

---

roles/logstash/templates/logstash.conf.j2

Fixes #920  where logstash was being configured to send both master and agent logs on all nodes.

Fix #920 logstash conditional

---

roles/chronos/defaults/main.yml
roles/chronos/tasks/main.yml
roles/marathon/defaults/main.yml
roles/marathon/tasks/conf.yml
roles/mesos/defaults/main.yml
roles/mesos/tasks/leader.yml

Parttialy revert to wait-for-zookeeper script, but still use
wait_for to check consul registration.
Set ACLs only on once node of clusters via local interface

Use inventory_hostname for setting ACLs

---

terraform/openstack-floating.sample.tf
terraform/openstack.sample.tf

Users should be aware of this variable which is missing in OpenStack
Terraform sample files.

Add edge_data_volume_size to Terraform samples

---

terraform/gce/disk.sh

The script currently runs:
`sudo rpm -qa kernel | sed -e 's/^kernel-//' | xargs -I {} dracut -f /boot/initramfs-{}.img {}`
which is effectively:
`"sudo rpm -qa kernel" | sed -e 's/^kernel-//' | xargs -I {} dracut -f /boot/initramfs-{}.img {}`
The `dracut` command requires the elevated rights so change `dracut` to `sudo dracut`

Fix sudo in terraform/gce/disk.sh dracut command

---

terraform/openstack-floating.sample.tf
terraform/openstack.sample.tf

Allows to choose SSH user depending on the image. Related to issue https://github.com/CiscoCloud/microservices-infrastructure/issues/947
Tested on CIS.

Include ssh_user in OpenStack Terraform examples

---

terraform/aws.sample.tf
terraform/aws/aws.tf

This adds the list of suggested AMI ids to the sample file, and a variable for the region. Users need only edit the region var and the rest of the configuration flows from that. This is for #866.

Add ami region mapping to sample file

---

Dockerfile

Docker builds are now linked up to the docker hub.

Update terraform in Dockerfile to 0.6.10

---

kubernetes.yml
kubernetes_vars.yml
playbooks/show-package-drift.yml
playbooks/trace-consul-wan-traffic.yml
playbooks/upgrade-packages.yml
playbooks/wait-for-hosts.yml
requirements.txt
roles/calico/tasks/kubernetes.yml
roles/calico/tasks/main.yml
roles/chronos/defaults/main.yml
roles/common/tasks/main.yml
roles/consul/tasks/nginx_proxy.yml
roles/dnsmasq/tasks/main.yml
roles/docker/defaults/main.yml
roles/docker/tasks/main.yml
roles/haproxy/handlers/main.yml
roles/k8s-master/tasks/testing.yml
roles/lvm/tasks/volume.yml
roles/marathon/tasks/jobs.yml
roles/mesos/defaults/main.yml
roles/vault/defaults/main.yml
roles/vault/tasks/bootstrap.yml
roles/zookeeper/handlers/main.yml
roles/zookeeper/tasks/main.yml

I installed ansible-lint to my mac and ran the linter for all the playbooks in the project. This PR adds the line for ansible-lint in requirements.txt, and begins to make the project compliant with the linter.
A big chunk of the linter errors were about trailing whitespace: I have taken care of those issues in the first commit. I have also made comments on lines where other warnings occurred, but the use of the `command` module here is because the main modules can't do what we need to do in those playbooks. 
The only other error is for `vault_init_json` string being broken up on multiple lines. This is a 'templating' issue.

Add ansible lint tool, fix reported issues

---

roles/docker/defaults/main.yml
roles/docker/tasks/main.yml
roles/glusterfs/tasks/server.yml
roles/lvm/tasks/volume.yml

This patchset contain  docker backing storage volume with XFS (and optionally BTRFS, which is still unsupported)

docker storage improvement

---

docs/upgrading/index.rst
playbooks/upgrade-0.5.1.yml
playbooks/upgrade-consul.yml
playbooks/upgrade-mesos-marathon.yml
roles/consul/tasks/nginx_proxy.yml

This updates the upgrade playbooks to be compatible with some of the recent PRs (consul, distributive, vault). I've tested on GCE and it works as an upgrade from 0.5.1 to the current master. I suggest we wait until we cut the first RC before more testing.
fixes #1048

update upgrade playbooks + docs

---

docs/faq.rst
docs/index.rst

Previously, the documentation did not include a FAQ section. This
patch adds a FAQ section with FAQs related to comparing Mantl with
OpenStack Magnum and Kubernetes.

Adds a FAQ Section to Documentation

---

addons/glusterfs.yml
playbooks/check-requirements.yml
playbooks/consul-join-wan.yml
playbooks/reboot-hosts.yml
playbooks/upgrade-mesos-marathon.yml
terraform.sample.yml

Tested on DO, deploys sucessfully
Unrelatedly, this also wraps the line of the ansible version requirement.

Remove kernel version requirement on digitalocean

---

addons/iptables.yml
roles/iptables/README.rst
roles/iptables/defaults/main.yml
roles/iptables/files/iptables-core.cfg
roles/iptables/tasks/main.yml
roles/iptables/templates/iptables-core.tmpl.j2
terraform.sample.yml

This role lets you restrict incoming IP traffic for the
cluster to only internal cluster members. A README file
describes more in detail how it works.

Add iptables role

---

roles/vault/tasks/bootstrap.yml

Attempts on persisting the token failed under Ansible 1.9.4 with the following error:
```
TASK: [vault | update security.yml with token] ******************************** 
failed: [172.17.16.66] => {"failed": true, "rc": 257}
msg: Destination security.yml does not exist !
FATAL: all hosts have already failed -- aborting
```
Using the `playbook_dir` variable fixes this issue. Additionally, errors on this task has been ignored as there is no value in failing on this one as, this is not run again unless run against new environments. The remaining steps can still continue safely with the variable in memory.

Fix vault root token persistence

---

roles/marathon/defaults/main.yml
roles/marathon/templates/mantl-api.json.j2

mantl-api: run on security-disabled clusters

---

plugins/inventory/terraform.py
terraform/gce.sample.tf
terraform/gce/instance/main.tf

fixes gce provisioning when using terraform 0.6.11+
This also fixes a couple of other minor issues when using the default gce sample file.

gce with terraform 0.6.11

---

roles/marathon/tasks/jobs.yml

this runs on control nodes in most environments and doesn't provide any benefit
obsoletes #1067
fixes #1062

marathon: don't pull down docker images in advance

---

docs/getting_started/aws.rst

AWS documentation updates.
- Security setup needed to satisfy cert upload for terraform.
- We dont store AWS creds in the aws.tf file anymore (provide info on ~/.aws/ usage)
- Help on common pip/yaml issues when running ./security_setup
- Make the flow easier to understand (what is necessary to do versus info)
- Comments, feedback and observations from a room of people following the docs.

Update AWS Documentation 

---

roles/dnsmasq/README.rst
roles/dnsmasq/defaults/main.yml
roles/dnsmasq/tasks/main.yml
roles/dnsmasq/templates/20-kubernetes
roles/dnsmasq/templates/90-base
roles/dnsmasq/templates/resolv.conf.j2

Consul DNS Package

---

terraform/vsphere/main.tf

vSphere provider for Terraform seems to use `custom_configuration_parameters` instead of `configuration_parameters` now. Reference is [here](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html). Also, I can't find any information about the `connection` arguments. Is this still valid?

vSphere Parameter Update

---

.github/PULL_REQUEST_TEMPLATE.md

This should still be a requirement, but it's not helpful to have in the template because it can't really be evaluated until after all discussion and testing is finished. Having another box to check also means that in
Github's UI there are a lot of issues that have 3/4 requirements checked where the fourth is the rebase requirement, and which are otherwise completely ready for merge.

pull request template: remove rebase requirement

---

docs/getting_started/aws.rst
terraform/aws.sample.tf
testing/aws.tf

Docs update removes literal inclusion of text from `aws.sample.tf`, replaces it with dynamic include.
Fixes #1178

Update AMIs, remove references to old ones

---

roles/consul/README.rst
roles/consul/defaults/main.yml
roles/consul/templates/consul.json.j2

consul: default log level of 'warn'

---

roles/common/tasks/main.yml

See #811 
The default NTP client chonry isn't pre-installed on all CentOS 7 System

common: add chrony

---

roles/dnsmasq/README.rst
roles/dnsmasq/defaults/main.yml

This version adds search paths for .consul and .node.consul. This means
that where one had to type `x.node.consul` before, `x.node` and `x` will
be resolved just the same.
This also means that services can be addressed using the shorter names:
`zookeeper.service.consul` becomes `zookeeper.service`, for instance.

dnsmasq: upgrade mantl-dns to 1.1.0

---

roles/dnsmasq/tasks/main.yml

Using the `latest` behavior means that we get the latest version despite specifying a version. Using `installed` fixes this.
When testing, you should se the following output:
```
$ rpm -qi mantl-dns
Name        : mantl-dns
Version     : 1.0.0
Release     : 3.centos
Architecture: x86_64
Install Date: Thu 10 Mar 2016 11:40:42 PM UTC
Group       : default
Size        : 332
License     : ASL 2.0
Signature   : (none)
Source RPM  : mantl-dns-1.0.0-3.centos.src.rpm
Build Date  : Thu 10 Mar 2016 11:03:34 PM UTC
Build Host  : testing-worker-linux-docker-f69df972-3474-linux-3.prod.travis-ci.org
Relocations : /
Packager    : <travis@testing-worker-linux-docker-f69df972-3474-linux-3>
Vendor      : Asteris
URL         : https://github.com/asteris-llc/mantl-packaging
Summary     : DNS integration with …
```

dnsmasq: don't get latest version

---

roles/common/tasks/main.yml
roles/traefik/handlers/main.yml
roles/traefik/tasks/main.yml
roles/traefik/templates/marathon.conf.j2

traefik: wait for marathon before starting (smlr)

---

roles/logrotate/files/mesos
roles/logrotate/tasks/main.yml
roles/logstash/templates/logstash.conf.j2
roles/mesos/handlers/main.yml
roles/mesos/tasks/main.yml
roles/mesos/templates/mesos-agent.sysconfig.j2
roles/mesos/templates/mesos-master.sysconfig.j2

- don't use MESOS_LOG_DIR
- stdout/stderr is logged to journal
- rsyslog sends mesos-master and mesos-agent logs to files
- updated logrotate config
- updated logstash rules
Fixes #764

mesos: refactor logging

---

roles/common/tasks/main.yml

When deploying Mantl via ansible-playbook, an assumption is made that the OS already has yum-utils installed when trying to increase the yum timeout, failing the deployment if yum-config-manager is not present. 
Added a task that can install yum-utils (contains yum-config-manager) as a prerequisite.

adding task during ansible-playbook to install yum-utils

---

docs/getting_started/vsphere.rst
terraform/vsphere.sample.tf
terraform/vsphere/main.tf

Works against ESXi 6.0, template needs to have the latest VMware tools installed, or else the customization will not work.

patch use builtin vsphere provider

---

roles/mesos/templates/mesos-agent.sysconfig.j2
roles/mesos/templates/mesos-master.sysconfig.j2

This forces mesos to bind to the private IP of the instance

Add --ip option for mesos agents and master

---

terraform/aws/instance/main.tf

The list of hostnames can be sent to external dns
modules for creating records.

Adds an output for hostnames

---

.gitignore

This will ensure folks don't check in .tf files holding secrets. It only affects files in the project root directory, so it will still pick up modified files under `terraform/`.

gitignore: don't check in terraform secrets

---

terraform/aws.sample.tf
terraform/aws/aws.tf
terraform/aws/instance/main.tf

This resolves https://github.com/CiscoCloud/mantl/issues/1277

make dns and route53 names consistent with /etc/hosts

---

addons/elk.yml
roles/logstash/handlers/main.yml

As of https://github.com/CiscoCloud/mantl/pull/1180, logstash would only be installed on control nodes when the ELK addon is deployed. This PR updates the addon so that logstash is installed on all nodes.

logstash: install on all nodes when installing elk

---

roles/consul/templates/consul.nginx.j2

When there are many nodes and services registered, the Consul UI can break when accessed through the nginx-consul proxy. This can occur when the internal nodes endpoint (`/v1/internal/ui/nodes`) returns more than 16K of data. The response is truncated and the UI fails (with an unintuitive `HTTP error code from Consul: 200 OK` "error"). This turns off `proxy_buffering` in the nginx config which resolves the problem.

consul: turn off proxy buffering in nginx conf

---

docs/getting_started/dns.rst
terraform/dnsimple/dns/main.tf

kubernetes: dnsimple support

---

docker.py

For whatever reason, I had the `--enable=false` flag passed into the security-setup script. I have a feeling this was copy-pasta. This will fix a whole class of Travis CI errors.

Enable security for CI testing

---

roles/mesos/templates/mesos-agent.sysconfig.j2
roles/mesos/templates/mesos-master.sysconfig.j2

This removes .node.consul from mesos registration, and only uses the ansible `inventory_hostname`. 
This is to fix external links (as in marathon)
from breaking on hosts that aren't in the .consul
domain.

Remove .node.consul from mesos hostnames

---

roles/common/tasks/main.yml

For minimal Centos targets
Fixes #1247

Add explicit dependency on libselinux-python

---

packer/scripts/ansible.sh
packer/vagrant.json
roles/distributive/tasks/main.yml
roles/repos/tasks/main.yml
vagrant/provision.sh

With these changes, it's possible to build a new box, switch the root Vagrantfile to use it, and vagrant up completely. It should also be easier to maintain, since it doesn't hardcode ansible roles.

Bring packer up to date with changes since 1.0

---

roles/haproxy/templates/haproxy.service.j2
roles/logstash/templates/logstash-service.j2
roles/mantlui/templates/nginx-mantlui.service.j2
roles/nginx/templates/nginx-consul.service.j2

fixes #1390
---
this works around the problem in https://github.com/CiscoCloud/mantl/pull/1239#issuecomment-215257670
When the error occurs, the `/var/lib/docker/containers/<containerid>` directory may get left behind but the container is removed and the service can be restarted.

force remove containers in systemd services

---

addons/kafka.yml
roles/kafka/README.rst
roles/kafka/defaults/main.yml
roles/kafka/tasks/main.yml
roles/kafka/templates/kafka-brokers.sh.j2
roles/kafka/templates/kafka.json.j2
roles/mantlui/defaults/main.yml

Installation documentation available in the role readme. Note that you will need at least 3 workers each with 1 CPU and 4 GB of memory available to Mesos in order to run with the default configuration.
This depends on https://github.com/CiscoCloud/nginx-mantlui/pull/18 being merged and the 0.6.8 tag of ciscocloud/nginx-mantlui being pushed to docker hub.
After successful Kafka installation (it can take a few minutes), verify the following:
- that the mantl/kafka scheduler is running and healthy in Marathon
- that there are 3 Kafka brokers running in Mesos (broker-1, broker-2, broker-3)
Once the brokers are up, you should be able to produce and consume data. Here is one example of a manual test:
```shell
curl -sku admin:password -d "topic=journal" …
```

kafka role

---

.travis.yml

Because we migrated to using a container based system, we no longer need
to install dependencies on the travis machine itself. So, I've removed
that line, and should speed up test runs

TRAVIS rm install step, containers have deps

---

roles/kubernetes-master/handlers/main.yml
roles/kubernetes-master/meta/main.yml
roles/kubernetes-node/handlers/main.yml
roles/kubernetes-node/meta/main.yml
roles/marathon/handlers/main.yml
roles/traefik/handlers/main.yml
roles/traefik/meta/main.yml

Instead, these roles will depend on the "handlers" role. Waiting on #1224 to remove the duplication in the addon roles.
Fixes #1343.
We should also think about removing duplicates of other handlers, like "reload systemd".
This is currently untested, since Vagrant isn't working and AWS is over quota. To test, just install chronos on a fresh mantl cluster.

Remove duplicate "reload consul" handlers in core roles

---

roles/docker/meta/main.yml

Useful if you run the Docker role by itself. Fixes this issue:
```
TASK: [docker | systemd drop-in for options] ********************************** 
ok: [lb0-worker-003] => (item=10-options.conf)
ok: [lb0-worker-001] => (item=10-options.conf)
ok: [lb0-kubeworker-002] => (item=10-options.conf)
ok: [lb0-worker-004] => (item=10-options.conf)
ok: [lb0-worker-002] => (item=10-options.conf)
ok: [lb0-kubeworker-001] => (item=10-options.conf)
ok: [lb0-edge-01] => (item=10-options.conf)
ok: [lb0-control-03] => (item=10-options.conf)
ok: [lb0-control-02] => (item=10-options.conf)
ok: [lb0-control-01] => (item=10-options.conf)
changed: [lb0-worker-003] => (item=12-network-options.conf)
changed: [lb0-worker-004] => (item=12-network-options.conf)
changed: [lb0-worker-001] => …
```

Add dependency on handlers role to docker role

---

testing/healthchecks.py

We originally added a two minute timeout to the health checks to allow
the cluster time to become healthy. Lately, there are a couple of checks
that may need more than two minutes, so we are going to increase it to
five.

[TRAVIS] Increase timeout for health checks

---

terraform/aws/instance/main.tf

---
* updated the aws terraform instance root volumes to use the gp2 type by
default
* configurable for root and attached volumes
* however, without manual configuration, the options are effectively limited to `standard` and `gp2` due to terraform limitations. The `io1` requires specifying `iops` on each volume but that setting is not compatible with the other types and cannot currently be conditionally included. If you want to set `io1`, you will also need to update `terraform/aws/instance/main.tf` to specify the `iops` attribute on the specific volume(s).
* I did not update the legacy `terraform/aws/aws.tf` terraform with this option.

aws: gp2 volume type for root device

---

roles/marathon/defaults/main.yml

fixes bug that occurs when using custom packages that don't have a framework attribute set

mantl-api: version 0.2.1

---

terraform/openstack/network/main.tf

We came across an openstack DC that didn't support
this and caused instances to never get IPs.
On existing openstack subnets, it will change the dhcp flag if it is set to false.

Ensure that DHCP is enabled for openstack subnets

---

terraform/openstack/instance/main.tf

This makes openstack blockstorage devices created by
terraform match the hosts they are attached to.

Ensure Openstack block storage matches hostname

---

docs/upgrading/index.rst
playbooks/upgrade-1.0.3.yml
playbooks/upgrade-consul.yml

Fixes #1392 
Fixes #1292 
Ready for review but extensive testing should wait until other 1.1 pull requests are merged.

add playbook for upgrading a 1.0.3 cluster to 1.1

---

docs/getting_started/vsphere.rst
roles/common/tasks/main.yml
terraform/vsphere.sample.tf
terraform/vsphere/main.tf

I've updated the vSphere provider code for: 
- to support Kubernetes 
- tested against the latest master branch 
- added support for linked-clones in vSphere (with caveats related to production, default still full clone) 
- updated vSphere Getting Started Doc 
- Fixed issue with directory cloud.cfg.d not getting created on providers without cloud init
- [n/a] Upgrades cleanly from the most recent release

Updated vSphere Support to Master and add Kubernetes

---

roles/mesos/files/mesos-leader-iptables.tmpl

When adding a worker node to an existing cluster, the previous iptables
template would block the new worker node from registering with the master.

Eliminate a race where a mesos agent could not connect to the master

---

docs/getting_started/bare-metal.rst
docs/upgrading/index.rst
roles/docker/tasks/main.yml

Fixes #1476
and includes some doc updates

Fix/docker upgrade 1.1

---

terraform/openstack-modules.sample.tf

provider/openstack: add ssh_user to kubeworker module

---

playbooks/upgrade-1.0.3.yml

this fixes a scenario where the upgrade playbook would fail if you have a cluster with mixed 1.0.3 and 1.1 nodes. collectd does not run (by default) on 1.1 nodes and the upgrade would fail if run against those nodes.

fix upgrade playbook for mixed clusters

---

Dockerfile

There are some provisioning scripts used within ansible that require
bash syntax in order to run. Previously, I didn't install bash in the
container because we were trying to keep the image simpler. However,
if we don't include bash, that means we have to refactor scripts to be
sh compatible, and that is not a good trade-off.

TRAVIS DOCKER Install bash for provisioning

---

roles/elasticsearch/tasks/uninstall.yml
roles/kibana/tasks/uninstall.yml

Fixes a bug where multiple mantl ui instances causes the curl -X DELETE task to fail due to multiple urls being present in mantl_api_url.stdout. Instead we choose the first.

Ensure package removal url is only one line

---

roles/elasticsearch/README.rst
roles/kibana/templates/kibana-mesos.json.j2

---
this does not actually affect functionality but, to avoid confusion, makes the elasticsearch-http value consistent with the actual configuration value used in the ELASTICSEARCH_SERVICE environment variable. see #1544

Consistent kibana elasticsearch-http value

---

playbooks/force-leader-election.yml

See discussion on #763, related to #566

Add playbook to force consul leader election

---

roles/elasticsearch/README.rst
roles/elasticsearch/defaults/main.yml
roles/kibana/README.rst
roles/kibana/defaults/main.yml

---
Increase the resources allocated for elasticsearch and kibana with the default configuration. Same testing process as #1481 but with a cluster that has sufficient resources.
I'm not sure what the correct balance is between providing a default configuration that doesn't require a huge investment in compute resources vs a configuration that might be appropriate for real workloads. Feedback welcome.

elk: increase default resources

---

playbooks/rolling-upgrade-packages.yml

When you run the rolling-upgrade-packages playbook, the yum refresh
cache task can time out, causing the playbook to fail. This in turn
causes CI tests to fail, and makes more work for our users.
I had this branch ready to go for some time, but I didn't make a PR. Sorry for that.

ANSIBLE remove yum refresh from upgrade playbook

---

terraform/aws.sample.tf

Git version: v1.0.3
`vpc_id` was removed from the `aws.sample.tf` and from the `terraform/aws/instance/main.tf` in https://github.com/CiscoCloud/mantl/commit/cae257257782b8e3cadd55b35276557f9f98f9f1#diff-e3a3c1dab01c11733dd82f3a01df46e7
This was not removed from the commented out sections for using remote state. If this was an accident, the attached PR resolves the issue.
This is the error shown when running (and goes away when removing it from `aws_sample.tf`)
```
$ terraform plan
...
Errors:
* 1 error(s) occurred:
* module root: module control-nodes: vpc_id is not a valid parameter
```

Remove vpc_id from aws.sample.tf in state_file sections

---

plugins/inventory/terraform.py

Adds the UCS provider from https://github.com/CiscoCloud/terraform.py/pull/43. Does not add UCS into Mantl yet, but will help when that's available.

terraform.py: sync from upstream

---

addons/16-overlay-network-options.conf.j2
addons/docker-overlay-networking.yml

Fixes #781
Tests here: http://pastebin.com/raw/DnZ2S8Bh
To test, install this addon on a fresh Mantl cluster, start two Docker containers on separate hosts and attach them to the same network like this:
```
(host 1) $ sudo docker run -it --net=overlay-net --name=container1 busybox
(host 2) $ sudo docker run -it --net=overlay-net --name=container2 busybox
```
and then see if they can ping each other by name.

addons: docker overlay networking

---

roles/certificates/defaults/main.yml
roles/certificates/tasks/main.yml

* uses random serial number
* doesn't depend on any certain cacert location
fixes #1551

Update generate-certificate to 0.1.1

---

playbooks/check-requirements.yml

This way, you don't get a bunch of `\n` in your error messages

nicer failure messages in check-requirements

---

roles/consul/files/consul-rolling-restart.sh

When the consul leader is restarted by the consul-rolling-restart.sh, the unlocking of the `locks/consul` node can fail with `500` because the Consul cluster isn't quite ready despite the `/v1/status/leader` consul endpoint reporting that there is a leader. Increase the time waiting for the cluster to settle.

Increase the time waiting for a consul leader to be elected

---

roles/chronos/meta/main.yml
roles/consul/meta/main.yml
roles/docker/meta/main.yml
roles/mantlui/meta/main.yml
roles/marathon/meta/main.yml
roles/mesos/meta/main.yml
sample.yml

As @ChrisAubuchon pointed out, as we move to dynamic configuration via Consul Template, people can enable security after the initial installation. Therefore, to avoid problems in that scenario, certificates should be generated on every installation, even those that don't need them atm. 
As a bonus, this will make our installation faster and the logs cleaner. 
Should fix #1628 since the certificates role will run before anything else that depends on it.

always run certificates role

---

playbooks/recreate-etcd-cluster.yml

I had issues with etcd when adding a new worker node to my cluster. The new worker was not able to join the existing cluster. This playbook will nuke the etcd data directory and restart etcd forcing etcd into new cluster mode where it allows new cluster members to join. 
There should be a way to programmatically add the new worker node however I was not successful in getting that to work... this is brute force and works.

Add playbook for recreating the etcd cluster

---

terraform/digitalocean.sample.tf
terraform/digitalocean/hosts/main.tf
terraform/digitalocean/keypair/main.tf
testing/terraform/do.tf

* rename `short_name` to `name`
* pass `name` to `do-keypair` and `do-hosts` by default
* reorder host-related variables

clean up digitalocean terraform configs

---

roles/mesos/README.rst
roles/mesos/defaults/main.yml
roles/mesos/templates/mesos-agent.sysconfig.j2

* By default, use cgroups/cpu,cgroups/mem which will enforce cpu and memory limits for tasks running under the mesos containerizer
---
This should be tested with and without calico.
Before this change, Mesos would not enforce cpu and memory limits for tasks running in the Mesos containerizer (non-docker tasks). This is now configurable but the default has changed and limits will now be enforced. Is this acceptable or should we change the default back to the prior setting?

mesos: configurable isolation setting for agents

---

roles/lvm/files/mantl-storage-setup.py

This fix also is a candidate to stable branch 1.2

lvm: fix parsing values of absolute amounts for volumes

---

.gitignore
security-setup

Less code is good code :recycle: 
from the commit message:
1. Remove unused argument `--no-verify-certificates`
2. Make `openssl_subject` part of the `Certificates` subclass instead of `Component`, as it's unused anywhere else
3. Don't generate serial or index.txt, we only needed those for generating certificates.
4. The CA must be generated if there's only a key present - we distribute the cert!
5. Make the root CA valid for 10 years instead of 1 year. The root CA should always be valid for as long as possible! We should generate an intermediate CA if we want it to be short-lived.

security-setup: Clean up root CA generation

---

roles/etcd/defaults/main.yml

This is the latest version in the Centos repos. 
Related: #1678

etcd: upgrade to 2.2.5

---

roles/dnsmasq/README.rst

dnsmasq readme: remove shortened consul dns names

---

terraform/openstack/floating-ip/main.tf
terraform/openstack/hosts-floating/main.tf

This patch switches openstack_compute_floatingip_v2 (nova) to openstack_networking_floatingip_v2(neutron) because neutron is the proper method in which to handle the networking.

Change OpenStack compute_floatingip to networking_floatingip

---

group_vars/all/kubernetes_vars.yml
roles/kubernetes/README.rst
sample.yml
terraform/gce/instance/main.tf

--- 
This allows kubernetes to manage things like Load Balancers and persistent volumes.
* enables cloud provider integration by default on gce
* adds service account scopes to gce instances
_Note: if you do not clean up kubernetes-created resources (like load balancers) in advance, terraform may not be able to destroy your cluster._
You can test the cloud integration by creating a Service with `type: LoadBalancer`. You can use the Kubernetes guestbook as an example. If you uncomment https://github.com/kubernetes/kubernetes/blob/master/examples/guestbook/all-in-one/guestbook-all-in-one.yaml#L130 and then run `kubectl create -f examples/guestbook/all-in-one/guestbook-all-in-one.yaml`, you should end up with a Load Balancer exposing the guestbook app externally. You can get the load …

kubernetes gce cloud integration

---

roles/consul/defaults/main.yml
roles/repos/defaults/main.yml

---
WIP: not ready to merge. currently we get the following error:
`No Package matching 'distributive-0.2.5-1' found available, installed or updated`
We either need to push the `distributive-0.2.5-1` package into the repo or switch mantl to use distributive `0.3.0-1` but not sure of the status.
ping @siddharthist @Zogg

use mantl 1.3 repo

---

.travis.yml
Dockerfile
terraform/aws/aws.tf
terraform/aws/instance/main.tf
terraform/aws/route53/dns/main.tf
terraform/clc/node/main.tf
terraform/digitalocean/hosts/main.tf
terraform/gce/gce.tf
terraform/gce/instance/main.tf
terraform/openstack/hosts-floating/main.tf
terraform/openstack/hosts/main.tf
terraform/openstack/network/main.tf
terraform/softlayer/hosts/main.tf
terraform/triton/instance/main.tf
terraform/vsphere/main.tf

As far as I understand this shouldn't be a compatibility problem, in the terraform 0.6 line the escaped-quotes bug was preserved for compatibility, and that bug was removed in 0.7. However, the unescaped-quotes method has been the correct format for quite some time.

[terraform 0.7] fix compatibility with new terraform

---

roles/docker/defaults/main.yml
roles/docker/files/20-ExecStart.conf.j2

disable legacy registries. fixes #1668 
remove unused REGISTRY variables
disable inter-container networking. fixes #1669 
fresh install tested on aws. needs upgrade testing.

Minor docker security improvements

---

terraform/aws/vpc/main.tf

@sehqlr,
Fix for issue: #1807 
changed concat command to variable reference in  terraform/aws/vpc/main.tf

updated concat function, which has been repurposed

---

roles/lvm/files/mantl-storage-setup.py

tiny fix for `mantl-storage-setup.py`
``` python
>>> import os                                                                                                                                          
>>> os.sleep
Traceback (most recent call last):                                                                                                                     
File "<stdin>", line 1, in <module>                                                                                                                  
AttributeError: 'module' object has no attribute 'sleep'                                                                                               
>>> import time …
```

mantl-storage-setup.py fix for AttributeError

---

roles/mantlui/defaults/main.yml

currently roles/mantlui/defaults/main.yml specifies nginx-mantlui version 0.7.1
This will cause mesos ui to fail as an empty upstream in the nginx.conf file is created for
kubernetes_api (copy and paste error, it is looking for service mesos).
This bug will only be seen if consul reports no kubernetes.
Symptoms:
mesos ui continually says "unable to connect to <mantl controller:443>"
mesos itself is running fine and marathon has no problem.
/var/log/nginx/error.log
2016/12/01 18:53:59 [emerg] 399#0: no servers are inside upstream in /etc/nginx/nginx.conf:36
This is fixed by the Aug 22 commit to nginx-mantlui
https://github.com/CiscoCloud/nginx-mantlui/blob/master/nginx.tmpl
which is included in the 0.7.2 nginx-mantlui container

bump nginx-mantlui container to 0.7.2

---

docs/getting_started/index.rst

You were missing a new line in the "Getting started" index page, added it to fix the broken table of contents.

Fix broken second table of contents

---

packer/scripts/ansible.sh

The epel repository used to download ansible when building the packer box does not exist:
```
curl -I http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-6.noarch.rpm
HTTP/1.1 404 Not Found
Date: Thu, 22 Sep 2016 17:20:28 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips
Content-Type: text/html; charset=iso-8859-1
```

Use epel-release package 

---

roles/glusterfs/defaults/main.yml
roles/glusterfs/tasks/main.yml

The glusterfs repo has changed and is now in the CentOS Extras repository and Ansible provisioning fails because of this, please merge this to fix problem.
More info about changed repo at:
https://download.gluster.org/pub/gluster/glusterfs/3.7/LATEST/CentOS/

Updated outdated glusterfs repo, use EPEL repo instead

---

roles/lvm/files/mantl-storage-setup.service

Updates mantl-storage-setup unit to avoid possible circular dependency with local-fs.target. Tested on bare-metal.
> Unless DefaultDependencies= in the "[Unit]" is set to false, service units will implicitly have dependencies of type Requires= and After= on sysinit.target, a dependency of type After= on basic.target as well as dependencies of type Conflicts= and Before= on shutdown.target. These ensure that normal service units pull in basic system initialization, and are terminated cleanly prior to system shutdown. Only services involved with early boot or late system shutdown should disable this option.
References
[1] [systemd.service — Service unit configuration](https://www.freedesktop.org/software/systemd/man/systemd.service.html#)
[2] [structural overview of well-known units and …

possible circular dependency in mantl-storage-setup.service

---

.travis.yml
testing/travis.py

The logic for skipping builds for PRs vanished, so I added it back in,
expanding the `filter_doc_files` into a skip function. It takes the list
of changes, and returns a bool. Other skipping logic could go in here

[TRAVIS] Expand skipping logic in travis.py

---

roles/vault/defaults/main.yml
roles/vault/templates/vault.unseal.j2

This in order to avoid unexpected end-of-line in a file /usr/local/bin/vault-unseal.sh
This causes error because a {{ key }} variable is perceived as a command

Use list for vault_command_options variable

---

vagrant/provision.sh

7.6 no longer exists. It is 7.9

Point to correct version of RPM

---

roles/certificates/defaults/main.yml

On AWS there namepaces are in the assets names then no log key access on k8 works
This adds the aws *.ec2.internal namespace to the set of keys

Added aws ec2.internal namespace keys

---

roles/certificates/defaults/main.yml
terraform/aws/iam/main.tf

Fixed aws role(s) in the main of aws/iam/main.tf :: Only one role can be allocated not a list of roles

Fixed typo in dns host name for aws instances

---

roles/calico/templates/calico-plugin.conf

Include `k8s_api_root` option in cni plugin configuration. This will probably resolve all issues we currently have with kube2dns and k8s dashboard containers. 
Please do not merge until we double check it.

[WIP] Update cni plugin configuration for calico v2.1

---

roles/calico/files/neutron_port_update.py

In some OpenStack labs, the publicURL for neutron may not be configured
as expected. Add missing slash if needed.

Add last missing slash: Fixes issue #1779 

---

plugins/inventory/terraform.py
terraform/aws/elb/main.tf
terraform/aws/instance/main.tf

When deploying to AWS and using an ELB it is possible for all Mantl instance roles to live in a private subnet. In this deployment scenario public ip addresses are not required (and worse can be confusing to users looking at these instances). 
This PR adds a tfvar to the `aws/instance` module so that users of this module (namely `aws.tf`) can specify a private subnet and prevent the assigning of a public ip address should one decide to deploy in this configuration. Additionally the private ips for the instance are output for use by other terraform resources. 
This change is backwards compatible for all existing aws.tf customizations.
I am happy to address relevant documentation changes if someone can help me identify them. I searched for `private` on docs.mantl.io and did not find any …

Adds support for private ip only AWS instances

---

addons/collectd-monasca.yml
roles/collectd-monasca/README.rst
roles/collectd-monasca/defaults/main.yml
roles/collectd-monasca/handlers/main.yml
roles/collectd-monasca/tasks/main.yml
roles/collectd-monasca/templates/collectd.conf.j2
roles/collectd-monasca/templates/collectd.service.j2

Add collectd-monasca role that deploys custom collectd code to send monasca style metrics to Kafka.

Add collectd-monasca role that deploys custom collectd code

---

roles/common/tasks/main.yml

On CentOS 7, journald is set to persist logs across boots only if a
file is created by a system administrator. With this commit, we add a
line to the journald config file to persist the log data.

[JOURNALD] Enable persistent storage for journal

---

roles/disk/README.rst
roles/disk/defaults/main.yml
roles/disk/meta/main.yml
roles/disk/tasks/main.yml
roles/disk/templates/90-mantl-data-volume.conf.j2
roles/elasticsearch/defaults/main.yml
roles/elasticsearch/templates/elasticsearch.json.j2
roles/kafka/defaults/main.yml
roles/mesos/defaults/main.yml
roles/mesos/meta/main.yml
roles/mesos/tasks/follower.yml
roles/mesos/templates/40-mesos-data-volume.conf.j2
sample.yml

---
- configures mesos to use the external volume for its work directory (on lvm-backed platforms)
- adds new disk role to mount /mnt/mantldata using the remainder (by default) of the available space of the external disk  (on lvm-backed platforms)
- configures elasticsearch to use external disk for data storage (by default)
- configures kafka to use external disk for data storage (by default)
_When testing, make sure you update your local `mantl.yml` with the changes in `sample.yml`._
---
worker node:
``` shell
--- Physical volume ---
PV Name               /dev/sdb
VG Name               mantl
PV Size               100.00 GiB / not usable 4.00 MiB
Allocatable           yes (but full)
PE Size               4.00 MiB
Total PE              25599
Free PE               0
Allocated PE …
```

mantldata volume + external disk for mesos, kafka, and elasticsearch

---

.travis.yml

- N/A Installs cleanly on a fresh build of most recent master branch
- N/A Upgrades cleanly from the most recent release
- N/A Updates documentation relevant to the changes
Our CI builds do not currently preserve state between builds. When
the destroy step doesn't trigger properly, infrastructure can hang
around, and that causes cascading quota failures in subsequent builds.
We could cache the tfstate within Travis, but that doesn't allow any
other tools access to the tfstate, which would be useful for external
tools. Therefore, we can use remote tfstate to allow for state to
persist, as well as expose the information to other tools we may create.
Supercedes and closes #1718

[TRAVIS] Use remote tfstate to simplify CI ops

---

shell.nix

Add shell.nix with definition of all requirements including ssh, terraform, packer, ansible, and tools needed for ./security-setup

Add shell.nix with definition of all requirements

---

roles/etcd/templates/etcd.conf.j2
roles/vault/defaults/main.yml

- Use of etcd_peer_url_scheme should just be etcd_url_scheme
- Removed usage of consul_dns_domain

Fixes two ansible build issues

---

etcd.yml
roles/vault/README.rst
roles/vault/defaults/main.yml

Current master is failing with the error below:
```
TASK: [vault | configure vault] *********************************************** 
fatal: [control-01] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dns_domain' is undefined", 'failed': True}
fatal: [control-01] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dns_domain' is undefined", 'failed': True}
```
Since mantl 1.2 the `consul_dns_domain` ansible var is no longer in use.

Remove obsoleted consul_dns_domain ansible var

---

DCO

Inspired by http://elinux.org/Developer_Certificate_Of_Origin
Will leave it up to other committers if they feel is a appropriate change.

Adding developer certificate of origin

---

packer/kickstarts/vagrant.cfg
packer/scripts/vagrant.sh
packer/scripts/vbox.sh
packer/vagrant.json
vagrant/README.rst

Issues resolved:
- ### Fix for #1399 "unknown filesystem type 'vboxsf'. 
Cause: You were missing the (proper version of) the guest additions in the box.
You need to install a plugin to install/upgrade these at .vagrant up' time.
`vagrant plugin install vagrant-vbguest`
**packer/scripts/vbox.sh** now mounts  the version of VBoxGuestAdditions that corresponds to your version of VirtualBox.
Hardcoded version removed.
Finally the guest can mount folders using this in the Vagrantfile:
`config.vm.synced_folder ".", "/vagrant"`
- ### Fix for #1891 "Update Vagrant box"  Now 1611 Centos 7 iso
[Verify checksum against](https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7#head-9e717f2e95c7cb447ef66c0a0ae1315027b67684)
`"27bd866242ee058b7a5754e83d8ee8403e216b93d130d800852a96f41c34d86a"`
- …

First step in getting packer to work again.
