roles/marathon/README.rst, roles/marathon/defaults/main.yml, roles/marathon/tasks/conf.yml, roles/marathon/tasks/main.yml
This PR addresses issue #67.
Unless I hear otherwise, I'll merge this 3/7. It makes no changes by default, only when you set the variables provided.
=> Marathon UI authentication

roles/marathon/README.rst, roles/marathon/defaults/main.yml, roles/marathon/tasks/conf.yml, roles/marathon/tasks/framework_auth.yml, roles/mesos/README.rst, roles/mesos/defaults/main.yml, roles/mesos/tasks/follower.yml, roles/mesos/tasks/leader.yml, roles/mesos/tasks/main.yml, roles/mesos/templates/master-credentials.j2, roles/mesos/templates/master-defaults.j2
This adds follower and framework authentication to Mesos. It will close #67.
If I don't hear anything about this by Monday 3/9, I'm going to merge this. Like #75, it makes no changes by default. All security at this point is opt-in.
=> Mesos follower and framework authentication

examples/hello-world/README.md, examples/hello-world/launch.sh
1. `-u | --user` user to use for request.
1. `-p | --password` password to use for request.
resolve #112
=> Add parameters to hello-world example for authentication.

roles/dnsmasq/handlers/main.yml, roles/dnsmasq/tasks/main.yml
Ensure NetworkManager package is installed.
Ensure dnsmasq.d directory exists.  
Set proper permission on 10-consul - it won't execute otherwise (dnsmasq fails to start if 10-consul isn't executable)
Ensure to restart NetworkManager after reconfigurations
=> Updates to work with Centos7 cloud image

requirements.txt, roles/common/tasks/main.yml, roles/nginx/tasks/main.yml, security-setup
Reverts CiscoCloud/microservices-infrastructure#130. See issue #138 for background.
=> Revert "Feature/nginx passwd"

inventory/group_vars/all/all.yml, roles/consul/templates/consul.json.j2, roles/dnsmasq/templates/10-consul, roles/docker/tasks/main.yml, roles/marathon/defaults/main.yml, roles/mesos/defaults/main.yml, roles/zookeeper/templates/zookeeper-env.j2
* Use `consul_dns_domain` in `inventory/group_vars/all/all.yml` to set the Consul DNS domain
=> Move consul DNS domain to a variable

inventory/group_vars/all/users.yml
Users dict wasn't formatted correctly
=> Fix users variables in inventory/group_vars/all/users.yml

roles/common/tasks/main.yml
This pull request disables and stops firewalld if it's enabled.  NOOP if it isn't.
=> disable firewalld - fixes #193

requirements.txt
=> Update minimum version of novaclient for #192

roles/consul/files/consul.nginx, roles/consul/tasks/main.yml, roles/consul/templates/consul.json.j2, roles/consul/templates/consul.nginx.j2, roles/marathon/templates/marathon.nginx.j2, roles/mesos/templates/mesos-leader.nginx.j2, security-setup
added --no-ssl option to security-setup
=> #176 security-setup: disable auth in command line

roles/vault/tasks/bootstrap.yml
Only update variables when Vault is not already initialized
=> Limit execution of Vault bootstrap tasks

inventory/1-datacenter, kafka.yml, roles/kafka/README.md, roles/kafka/defaults/main.yml, roles/kafka/tasks/client.yml, roles/kafka/tasks/main.yml, roles/kafka/tasks/scheduler.yml, roles/kafka/templates/kafka.json.j2, roles/mesos/defaults/main.yml, site.yml
- Step 1: get kafka-mesos repo from github, build it and download
kafka binary from Apache site
- Step 2: Setup kafka scheduler using docker container and push it
like app to marathon
- Step 3: Add 3 brokers and start them at mesos cluster using
kafka-mesos.sh utility
IssueID: none
=> Add Kafka role

roles/vault/handlers/main.yml
=> Issue #231: Fix vault restart

roles/consul/tasks/main.yml
When acl_master_token is changed ceonsul requires restart, not reload
=> Consul requires restart on acl_master_token change

roles/consul/files/consul-acl-bootstrap.sh, roles/consul/tasks/acl.yml, roles/consul/tasks/main.yml, roles/consul/tasks/noacl.yml, roles/consul/templates/acl.json.j2, roles/consul/templates/agent_acl.json.j2, security-setup
Updated for consul 0.5.1 and upsert functionality for ACLs
=> Feature/consul 0.5.1

roles/consul/files/docker-service.json, roles/consul/tasks/main.yml, roles/docker/files/docker-service.json, roles/docker/tasks/main.yml
Docker is trying to register in Consul though the last one is not
installed on this step yet.
=> Fix issue with Consul restart

roles/vault/tasks/main.yml
=> vault: wait for port to open

requirements.txt
=> Updated Ansible version constraint

roles/kafka/README.md, roles/kafka/defaults/main.yml, roles/kafka/tasks/client.yml, roles/kafka/tasks/main.yml, roles/kafka/tasks/scheduler.yml, roles/kafka/templates/kafka.properties.j2, roles/kafka/templates/kafka.sh.j2
- installation folder renamed to kafka-mesos instead kafka
- utility kafka-mesos can be runing just in it install folder
- use kafka-mesos.property file to setup all configuration
RequestID: internal
=> Improve kafka-mesos role

.dockerignore, Dockerfile
Provides a complete environment for running MI with all dependencies
installed and ready to go.
Also acts as base image for allowing deployers to include their custom
setup (inventory, variables, and security).
=> Add Dockerfile to provide operational environment.

docs/kafka.md, roles/kafka/tasks/client.yml
Increase time to wait kafka scheduler to 1800 sec
Add kafka.md to docs with short kafka usage guide
IssueID: Internal
=> Increase kafka timeout and add documentation

roles/haproxy/defaults/main.yml, roles/haproxy/templates/haproxy.service.j2
Fixes  #241 SSL cert issues in consul template with self-signed certs.
=> Add ssl args to the haproxy container

docs/getting_started/aws.rst, docs/getting_started/index.rst, terraform/aws.sample.tf
* added a new aws section to the getting started guide
=> docs(aws): first version of aws documentation

plugins/inventory/terraform.py, requirements.txt, tests/inventory/terraform/conftest.py, tests/inventory/terraform/test_common.py, tests/inventory/terraform/test_gce.py, tests/inventory/terraform/test_openstack.py
Uses py.test. Check out the new entry in `requirements.txt` and then run `py.test`.
=> Test terraform.py

roles/consul/defaults/main.yml, roles/consul/tasks/main.yml, roles/consul/templates/health-check.json.j2, roles/consul/templates/health-check.sh.j2
Load average, memory, disk space checks  will be available through web UI
=> Feature enable consul system health checks 

tests/inventory/terraform/test_aws.py
```
=================================================== test session starts ====================================================
platform darwin -- Python 2.7.9 -- py-1.4.28 -- pytest-2.7.1
rootdir: /Users/brianhicks/code/asteris/microservices-infrastructure, inifile: 
collected 87 items
tests/inventory/terraform/test_aws.py ................................
tests/inventory/terraform/test_common.py .....
tests/inventory/terraform/test_gce.py ..........................
tests/inventory/terraform/test_openstack.py ........................
================================================ 87 passed in 0.32 seconds =================================================
```
=> terraform: test AWS parser

roles/exhibitor/README.rst, roles/exhibitor/defaults/main.yml, roles/exhibitor/handlers/main.yml, roles/exhibitor/tasks/main.yml, roles/exhibitor/templates/exhibitor-service.j2, site.yml
[Exhibitor](https://github.com/Netflix/exhibitor/wiki) is a Java supervisor system for ZooKeeper.
In this feature only for backup/restore of zk transactions from zookeeper-data-volume container.
=> Exhibitor for issue #259

roles/logrotate/files/zookeeper, roles/logrotate/tasks/main.yml, roles/logstash/templates/logstash-service.j2, roles/logstash/templates/logstash.conf.j2, roles/zookeeper/tasks/main.yml, roles/zookeeper/templates/zookeeper-service.j2
the logstash container will mount the volumes from the zookeeper_data_volume container and use the file input to pull in the logs
=> logging: logstash grabs logs from zk data vol

roles/logstash/defaults/main.yml, roles/logstash/templates/logstash-service.j2
addresses part of https://github.com/CiscoCloud/microservices-infrastructure/issues/276
=> use ciscocloud/logstash:0.2 for logstash container

CHANGELOG.rst, README.md
Update changelog & read for 0.3.0-RC1
=> 0.3 changelog

roles/logstash/tasks/main.yml
=> authorize logstash syslog port when selinux enforcing

docs/getting_started/vsphere.rst, plugins/inventory/terraform.py, terraform/vsphere.sample.tf, terraform/vsphere/main.tf
This feature enables deployment a cluster with Terraform in vSphere environment.
The module uses third-party vSphere provider for Terraform.
For more detailed information regarding this module, please look at [README](https://github.com/CiscoCloud/microservices-infrastructure/blob/feature/terraform-vsphere/docs/getting_started/vsphere.rst) file.
=> Terraform vSphere feature

terraform/digitalocean/hosts/main.tf
Should we make the worker size bigger as well?
Fixes #489
=> terraform: increase DO control_size to 4gb

security-setup
looks like this now:
```
================ Consul ================
----> check security
----> gossip key
gossip key already set
----> master acl token
acl master token already set
----> agent acl token
acl agent token already set
----> SSL certificate
consul key already exists
consul certificate already exists
consul certificate is valid
----> Default ACL policy
consul_default_acl_policy already set
```
Closes #492
=> security-setup: s/disable security/check security/

examples/minecraft/README.md, examples/minecraft/minecraft.json
add a Minecraft server as a simple example app
=> examples(minecraft): add

README.md
addresses documentation fixes #509
=> added requirement of python 2 plus no-parallel

README.md
We've supported digital ocean since 0.3.1
https://github.com/CiscoCloud/microservices-infrastructure/releases
=> Changed digital ocean support checkbox to true

roles/marathon/defaults/main.yml
fixes #559 
should go after #549 is fixed
=> use version 0.2 of mesos-consul image

roles/chronos/tasks/nginx-proxy.yml, roles/consul/files/consul-acl-bootstrap.sh, roles/consul/tasks/main.yml, roles/consul/tasks/nginx_proxy.yml, roles/consul/tasks/noacl.yml, roles/marathon/tasks/nginx-proxy.yml, roles/mesos/tasks/nginx-proxy.yml
Replace curls to Consul with calls to `consul-cli kv-write`
=> Integrate consul-utils into the build.

docs/getting_started/openstack.rst
Updated documentation to include the openstack commands to get configuration values needed and steps for creating SSH keys and the openstack security group via the CLI.
=> Updated documentation for OpenStack

security-setup
=> security-setup: escape special characters in password

mi-deploy/README.md, mi-deploy/mi-deploy.go
That's all it takes to get softlayer support in mi-deploy.
=> mi-deploy also has support for SoftLayer

roles/glusterfs/README.rst, roles/glusterfs/defaults/main.yml, roles/glusterfs/tasks/main.yml
=> pin glusterfs version

roles/calico/defaults/main.yml, roles/chronos/templates/nginx-chronos.env.j2, roles/marathon/tasks/jobs.yml, roles/marathon/templates/nginx-marathon.env.j2, roles/mesos/templates/nginx-mesos-leader.env.j2
fix custom consul_dns_domain broken for calico, chronos, marathon and mesos roles
=> fix issue #668

roles/marathon/templates/marathon-wait-for-listen.sh.j2
See commit message.
This should be a trivial change. :-)
=> Trivial: Increase timeout for Marathon wait-for-listen

roles/chronos/tasks/main.yml, roles/marathon/tasks/conf.yml, roles/mesos/tasks/leader.yml
=> ensure zookeeper is responding before setting acls

terraform/gce.sample.tf
see https://github.com/hashicorp/terraform/pull/2839/
=> fixes deprecation warning using terraform 0.6.2+

terraform/gce.sample.tf, terraform/gce/gce.tf
- Use zone information during deployment.
- Allows user to set a zone for GCE
=> - Add default zone information to GCE.

mi-deploy/README.md
=> mi-deploy: Update README with link to binaries

mi-deploy/Makefile, mi-deploy/mi-deploy.go
=> mi-deploy: Makefile (for cross-compiling)

roles/consul-template/handlers/main.yml
Fix a consul-template systemctl typo.
=> Fix consul-template typo

roles/mantlui/defaults/main.yml, roles/mantlui/files/mesos/controllers.js, roles/mantlui/templates/mantlui.nginx.j2
Fixes:
preliminary testing indicates that this will work with Mesos 0.24+ (#739) but will need more testing before we can close that issue
=> mantlui: mesos and consul fixes

roles/docker/tasks/main.yml
=> use /etc/sysconfig/docker-local for safer upgrades

terraform/gce/disk.sh, terraform/gce/gce.tf
=> configurable root volume size on gce

roles/common/tasks/main.yml, roles/common/templates/hosts.j2
Should close issue #689 and #680
=> Use a template instead of regex to set hosts file

roles/common/files/10-root-nofiles.conf, roles/common/tasks/main.yml
=> Root ulimit increase

roles/chronos/templates/chronos-consul.j2, roles/marathon/templates/marathon-consul.j2
Testing the addition of timeouts to the health checks.
=> Adding in timeouts for health checks

roles/docker/defaults/main.yml, roles/docker/tasks/lvm.yml, roles/docker/tasks/main.yml, roles/docker/templates/docker-storage-setup.conf.j2, roles/glusterfs/defaults/main.yml, roles/glusterfs/tasks/server.yml, roles/lvm/defaults/main.yml, roles/lvm/tasks/main.yml, terraform.sample.yml, terraform/aws/aws.tf, terraform/gce/gce.tf, terraform/openstack.sample.tf, terraform/openstack/hosts-floating/main.tf, terraform/openstack/hosts/main.tf
LVM support implemented for openstack (both float and non-float IPs modes), AWS and GCE
=> Feature: lvm support

roles/docker/tasks/main.yml
Otherwise ansible will always execute it and showing it as "changed" on consecutive runs
=> Only update the docker.tar.gz when it needs to

docs/getting_started/openstack.rst
I've corrected some of the documentation. I would like someone to double check the changes.
=> Corrected floating ip documentation

docs/getting_started/cloudflare.rst, docs/getting_started/dns.rst, docs/getting_started/dnsimple.rst, docs/getting_started/gce.rst, docs/getting_started/index.rst, docs/getting_started/route53.rst, terraform/aws.sample.tf, terraform/cloudflare/main.tf, terraform/digitalocean.sample.tf, terraform/dnsimple/dns/main.tf, terraform/gce.sample.tf, terraform/gce/dns/main.tf, terraform/openstack-floating.sample.tf, terraform/openstack.sample.tf, terraform/route53/dns/main.tf, terraform/softlayer.sample.tf, terraform/vsphere.sample.tf
Following the discussion on #822, here's the changes made to support the edge roles.
Closes #822
=> Update DNS to deal with edge nodes

roles/zookeeper/files/zookeeper-update-mantl-0.5-0.6.sh, roles/zookeeper/tasks/main.yml
Folks, please check both  clean install and update from 0.5.0 tag.
Another issue still be, zk logs no more available to logstash, IDK if it really need (it not debug logs, it transaction logs -- db of zk)
=> Feature: zookeeper upgrade path

docs/security/security.rst, roles/common/defaults/main.yml, roles/common/tasks/main.yml, roles/docker/defaults/main.yml, roles/docker/tasks/main.yml, roles/k8s-minion/tasks/main.yml
- do not run docker with selinux-enabled by default
- centralize selinux policy/state settings
- run in permissive mode by default
fixes #613
=> selinux changes

examples/kong/deploy.sh
Correcting mistake $username:$username to $username:$password.
=> Fix authentication variable on cassandra check service step.

mantl-rename-faq.md
A basic tenet of the English language is that questions are denoted as such
using the question mark. Punctuation matters, @matjohn2!
Fixes.
=> Questions deserve question marks.

packer/vagrant.json, roles/docker/tasks/main.yml, roles/lvm/tasks/volume.yml
Move from vagrant.yml to terraform.sample.yml for the playbook
=> Add upgrade-packages.yml to packer build

roles/common/tasks/main.yml, roles/consul/tasks/acl.yml, roles/consul/tasks/main.yml, roles/dnsmasq/tasks/main.yml, roles/docker/tasks/collectd.yml, roles/glusterfs/tasks/server.yml, roles/kubernetes/tasks/gen_tokens.yml, roles/kubernetes/tasks/secrets.yml, roles/marathon/tasks/collectd.yml, roles/marathon/tasks/main.yml, roles/mesos/tasks/follower.yml, roles/mesos/tasks/leader.yml, roles/nginx/tasks/main.yml, roles/vault/tasks/bootstrap.yml, roles/zookeeper/tasks/collectd.yml, roles/zookeeper/tasks/main.yml
Fix issue #943. Start using full numeric notation in all playbooks.
=> Unify notation for file system permissions

roles/mantlui/defaults/main.yml
image does not contain .DS_Store files
fixes #960
=> updated mantlui nginx container tag

Vagrantfile, vagrant/README.rst
=> vagrant: add configurable list of playbooks to run

Vagrantfile, vagrant/README.rst
=> vagrant: edge node support

roles/marathon/defaults/main.yml, roles/mesos/defaults/main.yml, roles/mesos/tasks/follower.yml, roles/mesos/tasks/leader.yml, roles/mesos/tasks/main.yml, roles/mesos/templates/mesos-agent.sysconfig.j2, roles/mesos/templates/mesos-master.sysconfig.j2
=> mesos 0.25

roles/docker/files/dockerplugin.py
This fix will keep the plugin stable in highly loaded environment.
=> Fix for collectd-docker-plugin

terraform.sample.yml
=> Require Centos 7.2 via sample playbook

.gitignore, Vagrantfile
We really don't want to rsync or commit these huge directories!
=> Exclude Packer directories from Vagrant, Git

roles/marathon/tasks/conf.yml
Fixes #778
Closes #793 
Should be a simple change, but testing appreciated!
=> marathon: lock down config file

requirements.txt, terraform.sample.yml
Lays the groundwork for #806 and implements changes discussed there.
=> Require Ansible version in sample playbook

roles/traefik/defaults/main.yml
=> Update traefik for go 1.5.3 fix

roles/marathon/tasks/conf.yml, roles/marathon/tasks/jobs.yml
=> marathon: tighter perms on marathon conf dirs

examples/README.md, examples/hello-world/README.md, examples/minecraft/README.md
=> Update examples documentation

vagrant/provision.sh
Fixes #1023
Could you test and make sure this resolves the issue @TanyaCouture?
=> Fix vagrant failure when security-setup hasn't been run

examples/kong/kong.json
* Fixes the load balancing config to work with the latest version of Traefik
* Uses the Kong 0.6.0 final release (instead of RC3)
=> Kong example fix

roles/mantlui/defaults/main.yml
=> mantlui: bump nginx-mantlui version to 0.6.4

roles/marathon/defaults/main.yml, roles/marathon/templates/mantl-api.json.j2
supports frameworks that read mesos credentials from a file
=> mantl-api: version 0.1.4

terraform/aws.sample.tf
changed the control count from 2 to 3, which is required
=> changed the control count from 2 to 3, which is required

terraform/aws.sample.tf
role should be edge, pull up and default route53 vars
=> aws bugfix

roles/chronos/defaults/main.yml, roles/chronos/tasks/main.yml, roles/common/tasks/main.yml, roles/zookeeper/tasks/main.yml
Also contain commit which increase timeouts in yum,
=> Fix: replace mesosphere repo with direct links on packages

roles/logrotate/tasks/main.yml
=> Simplify logrotate role with loops

security-setup
see https://github.com/CiscoCloud/terraform.py/issues/24 for justification, mostly PEP 0394
=> python -> python2 in security-setup shebang

terraform/aws.sample.tf
add missed `worker_type`, `control_type`, `edge_type`
=> correct aws.sample.tf

roles/mesos/README.rst, roles/mesos/defaults/main.yml, roles/zookeeper/README.rst, roles/zookeeper/defaults/main.yml
=> Update mesos_cluster name to mantl!

addons/README.rst, docs/addons.rst, docs/index.rst
=> Add addons documentation

docs/components/index.rst
=> Add documentation on where to find our packages

roles/consul/README.rst
=> Fix consul_servers_group default documentation.

README.md
=> Add travis badge to README [ci skip]

examples/README.md
=> Fix typo in examples README

docs/getting_started/openstack.rst
=> Remove references to renamed openstack sample files

roles/common/files/asteris-mantl-rpm.repo, roles/common/files/ciscocloud-rpm.repo, roles/common/tasks/main.yml
See #1182 #1188.
We'll have to remove direct mantl package installs.
=> Add ciscocloud and asteris yum repos

addons/elk.yml, roles/elk/README.rst, roles/elk/files/kibana.yml.tmpl, roles/elk/handlers/main.yml, roles/elk/tasks/main.yml, roles/elk/templates/elasticsearch.json.j2, terraform/aws.sample.tf, terraform/digitalocean.sample.tf, terraform/softlayer.sample.tf, terraform/vsphere.sample.tf
* improved documentation including how to customize install and removing ELK
* scheduler cpu and ram configuration now actually take effect
* more resilient kibana configuration for elasticsearch url
* updates terraform sample configs so that clouds are more likely capable of running ELK by default
=> elk improvements

roles/lvm/defaults/main.yml
=> Add condition to check for definition of "provider"

roles/common/defaults/main.yml, roles/common/tasks/distributive.yml, roles/consul-template/tasks/main.yml, roles/consul/defaults/main.yml, roles/marathon/defaults/main.yml, roles/mesos/defaults/main.yml, roles/mesos/tasks/follower.yml, roles/mesos/tasks/leader.yml, roles/mesos/tasks/main.yml, roles/traefik/defaults/main.yml, roles/traefik/tasks/main.yml, roles/vault/defaults/main.yml, roles/vault/tasks/main.yml
See #1193 
Fixes #1182, #1194 
Tested on Vagrant
Next steps:
=> Install packages by name

roles/consul/defaults/main.yml
=> Derive defaults for consul_is_server variable

roles/marathon/tasks/main.yml
fixes #1183 
tested on aws. healthy cluster on a new build and after adding 2 new control nodes
=> marathon: generate consul service before iptables

docs/getting_started/vagrant.rst
=> Vagrant documentation in readthedocs

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
The [PR and Issue template feature released today](https://github.com/blog/2111-issue-and-pull-request-templates). These could really help us with triaging issues!
=> PR and issue templates

terraform/vsphere.sample.tf, terraform/vsphere/main.tf
Fixes #788
Needs testing on vSphere
cc @chrislovecnm
=> Configurable root volume size on vSphere

roles/docker/tasks/main.yml
satisfy yourself, go ahead and open the issue anyway and we'll help you test.
Feel free to delete this message once you're done. Thanks again!
Fixes #1257
=> docker: fix cloud-utils-growpart install

roles/logstash/files/logstash-elasticsearch.tmpl
Since the executors don't have a health check, if anything on the node is unhealthy they'll be taken out. This means we need to specify that we're OK with whatever the health happens to be.
=> logstash: take any service

README.md, docs/index.rst
* Removes duplicated information both within the README and between README and other docs
* Removes rename notice
* Updates list of features with current status
* Updates tagged versions
Fixes #1211
=> Update README for accuracy, especially "features"

roles/lvm/README.rst
=> Fixed typo in roles/lvm/README.rst

addons/elk.yml, roles/logstash/README.rst, sample.yml
Fixes #1130 
Tested and working both with and without ELK addon on DigitalOcean.
=> Move logstash role to ELK addon

terraform/gce.sample.tf
=> Fix typo in gce.sample.tf

terraform/cloudflare/dns-instance/main.tf, terraform/cloudflare/dns-roundrobin/main.tf, terraform/cloudflare/main.tf
untested. anyone with a cloudflare account that can verify?
=> cloudflare: consistent kubernetes naming in dns

roles/consul/defaults/main.yml
=> Update consul & consul-ui to 0.6.4

docs/getting_started/index.rst, docs/getting_started/triton.rst, playbooks/host-connectivity.yml, plugins/inventory/terraform.py, roles/nginx/tasks/main.yml, terraform/triton.sample.tf, terraform/triton/instance/main.tf, terraform/triton/keypair/main.tf, terraform/triton/network/main.tf
Upgrading is not applicable, this is a new target.
=> Add Joyent's Triton as a deploy target

docs/getting_started/triton.rst
- (n/a) Installs cleanly on a fresh build of most recent master branch
- (n/a) Upgrades cleanly from the most recent release
Doc-only change to update a page @misterbisson wrote for this purpose
=> docs(triton): change limits link to new page

roles/flannel/handlers/main.yml
=> flannel: start nginx-consul post docker restart

.gitignore
=> gitignore: ignore .syncdir/

roles/common/files/02_hostname.cfg, roles/common/tasks/main.yml
fixes #1231
---
* tested on AWS only so far. 
* will this work on other clouds?
* is this the best way to do it?
=> set persistent, friendly hostname

README.md
docs only: k8s is a core component now
=> README: add K8S to 'core components'

roles/kubernetes/README.rst
=> added kubeworker_type

CHANGELOG.md
=> docs: update changelog for 1.1 RC2

terraform/aws.sample.tf, terraform/aws/aws.tf, terraform/aws/vpc/main.tf
=> Change default vpc name to mantl

README.md
add links, alphebatize and categorize by completeness, add community supported platforms, remake markdown-toc
fixes #1505
=> readme: revamp supported platform section

README.md
=> readme: add clc to supported platforms

group_vars/all/main.yml, roles/common/tasks/main.yml
=> List cloud-init-providers in a variable

roles/marathon/defaults/main.yml, roles/mesos/defaults/main.yml
Just be sure to have packages in the repo before merging.
=> Upgrade Mesos to 0.28.2 and Marathon to 1.1.1

roles/vault/defaults/main.yml
waiting on CI build, mergable if that passes.
=> Vault 0.5.3

roles/traefik/defaults/main.yml
an updated package is forthcoming but this is needed so that master is not broken
=> traefik: package version 1.0.0

roles/etcd/templates/skydns.service.j2, roles/logstash/templates/logstash-service.j2, roles/nginx/templates/nginx-consul.service.j2
All limits are 10x normal usage.
Measurements here: http://pastebin.com/raw/z9yRJgq8
Progress on #1397
=> Add memory usage restrictions to Docker containers

roles/mesos/tasks/nginx-proxy.yml
untested, waiting on CI. 
it's not often we get to reduce the amount of code in our project!
ref #1526
=> use a loop to avoid duplication in nginx-proxy.yml

docs/getting_started/aws.rst
=> minor doc cleanup

docs/getting_started/gce.rst
=> Edits to docs/getting_started/gce

README.md, docs/index.rst
=> fixes #1612

docs/getting_started/bare-metal.rst
=> Copy edits to bare metal docs

docs/faq.rst
- [x ] Updates documentation relevant to the changes
=> New and updated FAQ's

group_vars/all/kubernetes_vars.yml, roles/kubernetes/README.rst, roles/mantlui/defaults/main.yml
fixes #1627
depends on https://github.com/CiscoCloud/nginx-mantlui/pull/24
=> k8s: ability to access k8s api remotely

roles/certificates/tasks/main.yml
=> certificates role: tag all tasks

roles/distributive/tasks/main.yml
should make our builds faster!
=> remove upgrade logic from distributive role

roles/kubernetes/files/make-ca-cert.sh
they are useful for debugging, and this script isn't run interactively.
=> make-ca-cert.sh: don't suppress errors

roles/consul-template/tasks/main.yml
Tested on DigitalOcean
fixes #1617
=> upgrade consul-template to v0.15

playbooks/check-requirements.yml
=> Check date before installing

docs/getting_started/index.rst
This  helps distinguish between supported and comunity suported platorms.check out PR #1584 for more information.
=> Added community-supported platforms to the getting started

group_vars/all/kubernetes_vars.yml
=> remove flannel configuration missed in the first purge

roles/marathon/defaults/main.yml
=> mesos-consul: v0.4.0

roles/certificates/tasks/main.yml
=> Delete CA private key after signing

roles/lvm/files/mantl-storage-setup.py
@sehqlr Sam, it should help with your reboot issues.
=> lvm/mantl-storage-setup: Wait for device appearing

Dockerfile
=> Updating docker file to point to new repo

.mention-bot
Cisco is no longer involved in the project. Taking their org out.
=> Update mention bot

.mention-bot
=> removing asters-llc

docs/security/security_setup.rst, roles/certificates/README.rst
bring the docs up to sync with the situation in master
=> update certificates/security-setup docs

roles/kubernetes/README.rst
- include LoadBalancer/Cloud Provider Integration
- discuss automatic Consul service registration
fixes #1656
=> k8s readme: update exposing services section

roles/certificates/defaults/main.yml
- [?] Upgrades cleanly from the most recent release
fixes #1810
=> make certs valid for k8s dns names

roles/lvm/files/mantl-storage-setup.py
=> [lvm] make sure mantl-storage-setup uses lvcreate -y

.travis.yml, testing/travis.py
=> Revert "[TRAVIS] Expand skipping logic in travis.py"

.travis.yml
=> Commenting out clouds we no longer have access to

roles/vault/defaults/main.yml, roles/vault/templates/vault.unseal.j2
=> Revert "Use list for vault_command_options variable"

roles/vault/defaults/main.yml, roles/vault/tasks/tls-auth.yml, roles/vault/templates/vault.unseal.j2, terraform/gce.sample.tf, terraform/gce/dns/main.tf
think i accidentally included the fix for project names as well.
git to go to sleep now though.
=> fix vault cli commands

terraform/gce.sample.tf, terraform/gce/dns/main.tf
add project_name since dns google_dns_record_set project field doesn't resolve project number.
=> fix  #1920 Error creating DNS RecordSet: googleapi: Error 404: Failed to find project

Vagrantfile, playbooks/check-requirements.yml, requirements.txt
=> Revert "Ansible 2.1"

playbooks/check-requirements.yml, requirements.txt
=> Sleep for k8

README.md
=> use mantl/mantl

README.md, roles/certificates/defaults/main.yml, terraform/aws/iam/main.tf
=> Revert "Rebase"

roles/calico/tasks/kubernetes.yml, roles/calico/tasks/main.yml, roles/calico/tasks/mesos.yml, roles/calico/templates/mesos-config.conf, roles/kubernetes/templates/kubelet.service.j2, roles/mesos/defaults/main.yml, roles/mesos/templates/mesos-agent.sysconfig.j2
=> Calico with Mesos CNI

roles/mesos/defaults/main.yml
=> use mesos 1.0.0

terraform/aws/security_groups/main.tf
=> parameterize allowed ingress cidr blocks for security groups

addons/filebeat.yml, roles/filebeat/defaults/main.yml, roles/filebeat/handlers/main.yml, roles/filebeat/tasks/main.yml, roles/filebeat/templates/filebeat.service.j2, roles/filebeat/templates/filebeat.yml.j2
Adds filebeat role that sends logs to Kafka.
=> Add filebeat role for sending logs to Kafka.

scripts/make-release.sh
Code should be self explanatory.
=> Script to ease making a release

roles/traefik/templates/traefik.toml.j2
One more shot! This configuration has worked for me.
=> enable ssl traefik endpoint

addons/journalbeat.yml, roles/journalbeat/defaults/main.yml, roles/journalbeat/handlers/main.yml, roles/journalbeat/tasks/main.yml, roles/journalbeat/templates/journalbeat.service.j2, roles/journalbeat/templates/journalbeat.yml.j2
Add journalbeat role that send journald logs to Kafka
=> Add journalbeat role that send journald logs to Kafka.

docs/getting_started/index.rst, roles/common/tasks/main.yml, roles/etcd/defaults/main.yml
I just changed the spacing to match the toctree above that did render correctly
=> Fix rendering of Community Supported links

roles/calico/files/neutron_port_update.py, roles/common/tasks/main.yml, roles/common/templates/hosts.j2, roles/elasticsearch/defaults/main.yml, roles/elasticsearch/templates/elasticsearch.json.j2, roles/etcd/tasks/main.yml, roles/etcd/templates/etcd.conf.j2, roles/logrotate/files/vault-ssh-helper, roles/logrotate/tasks/main.yml
Picked wanted changes from integ one role at a time.
Tested it and it builds and works
=> Cherry picking wanted integ changes from roles

vagrant/ansible.cfg, vagrant/debugger, vagrant/inventory
Adding 3 files so you can debug one role on vagrant using
`./debugger -l control-01 -t common`
=> A little trick to increase cycle time.

roles/mesos/defaults/main.yml, roles/mesos/meta/main.yml, roles/mesos/tasks/follower.yml, roles/mesos/templates/40-mesos-data-volume.conf.j2, roles/mesos/templates/mesos-agent.sysconfig.j2
Took all the mesos roles changes from integ. This upgrades Mesos to 1.0.0 plus add lvm
- [?] Updates documentation relevant to the changes
=> Picked mesos upgrade to 1.0.0 from integ

README.md
Removed spaces from columns in waffle.io. Fixed badge in readme.
=> Fix Waffle badge in README.md

roles/certificates/tasks/main.yml
=> uppdate certificates/tasks/main.yml

roles/repos/templates/asteris-mantl-rpm.repo
=> deprecated commands cleanup
